// This file was auto-generated by Fern from our API Definition.

package client

import (
	analytics "github.com/revkeen/revkeen-go/analytics"
	billing "github.com/revkeen/revkeen-go/billing"
	charges "github.com/revkeen/revkeen-go/charges"
	checkoutsessions "github.com/revkeen/revkeen-go/checkoutsessions"
	comms "github.com/revkeen/revkeen-go/comms"
	core "github.com/revkeen/revkeen-go/core"
	creditnotes "github.com/revkeen/revkeen-go/creditnotes"
	customers "github.com/revkeen/revkeen-go/customers"
	discounts "github.com/revkeen/revkeen-go/discounts"
	disputes "github.com/revkeen/revkeen-go/disputes"
	entitlements "github.com/revkeen/revkeen-go/entitlements"
	events "github.com/revkeen/revkeen-go/events"
	exports "github.com/revkeen/revkeen-go/exports"
	finance "github.com/revkeen/revkeen-go/finance"
	imports "github.com/revkeen/revkeen-go/imports"
	integrations "github.com/revkeen/revkeen-go/integrations"
	invoices "github.com/revkeen/revkeen-go/invoices"
	meters "github.com/revkeen/revkeen-go/meters"
	option "github.com/revkeen/revkeen-go/option"
	orders "github.com/revkeen/revkeen-go/orders"
	paymentintents "github.com/revkeen/revkeen-go/paymentintents"
	paymentlinks "github.com/revkeen/revkeen-go/paymentlinks"
	payments "github.com/revkeen/revkeen-go/payments"
	payouts "github.com/revkeen/revkeen-go/payouts"
	prices "github.com/revkeen/revkeen-go/prices"
	products "github.com/revkeen/revkeen-go/products"
	refunds "github.com/revkeen/revkeen-go/refunds"
	subscriptions "github.com/revkeen/revkeen-go/subscriptions"
	subscriptionschedules "github.com/revkeen/revkeen-go/subscriptionschedules"
	syncstate "github.com/revkeen/revkeen-go/syncstate"
	terminaldevices "github.com/revkeen/revkeen-go/terminaldevices"
	terminalpayments "github.com/revkeen/revkeen-go/terminalpayments"
	transactions "github.com/revkeen/revkeen-go/transactions"
	usage "github.com/revkeen/revkeen-go/usage"
	voids "github.com/revkeen/revkeen-go/voids"
	webhookendpoints "github.com/revkeen/revkeen-go/webhookendpoints"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *core.Caller
	header  http.Header

	Invoices              *invoices.Client
	Products              *products.Client
	CheckoutSessions      *checkoutsessions.Client
	Entitlements          *entitlements.Client
	Customers             *customers.Client
	Subscriptions         *subscriptions.Client
	Comms                 *comms.Client
	Analytics             *analytics.Client
	Finance               *finance.Client
	Payouts               *payouts.Client
	Refunds               *refunds.Client
	Voids                 *voids.Client
	CreditNotes           *creditnotes.Client
	Disputes              *disputes.Client
	Discounts             *discounts.Client
	PaymentLinks          *paymentlinks.Client
	Charges               *charges.Client
	Billing               *billing.Client
	Prices                *prices.Client
	Meters                *meters.Client
	Orders                *orders.Client
	Payments              *payments.Client
	Integrations          *integrations.Client
	SyncState             *syncstate.Client
	WebhookEndpoints      *webhookendpoints.Client
	PaymentIntents        *paymentintents.Client
	Events                *events.Client
	SubscriptionSchedules *subscriptionschedules.Client
	TerminalPayments      *terminalpayments.Client
	TerminalDevices       *terminaldevices.Client
	Usage                 *usage.Client
	Transactions          *transactions.Client
	Exports               *exports.Client
	Imports               *imports.Client
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: core.NewCaller(
			&core.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header:                options.ToHeader(),
		Invoices:              invoices.NewClient(opts...),
		Products:              products.NewClient(opts...),
		CheckoutSessions:      checkoutsessions.NewClient(opts...),
		Entitlements:          entitlements.NewClient(opts...),
		Customers:             customers.NewClient(opts...),
		Subscriptions:         subscriptions.NewClient(opts...),
		Comms:                 comms.NewClient(opts...),
		Analytics:             analytics.NewClient(opts...),
		Finance:               finance.NewClient(opts...),
		Payouts:               payouts.NewClient(opts...),
		Refunds:               refunds.NewClient(opts...),
		Voids:                 voids.NewClient(opts...),
		CreditNotes:           creditnotes.NewClient(opts...),
		Disputes:              disputes.NewClient(opts...),
		Discounts:             discounts.NewClient(opts...),
		PaymentLinks:          paymentlinks.NewClient(opts...),
		Charges:               charges.NewClient(opts...),
		Billing:               billing.NewClient(opts...),
		Prices:                prices.NewClient(opts...),
		Meters:                meters.NewClient(opts...),
		Orders:                orders.NewClient(opts...),
		Payments:              payments.NewClient(opts...),
		Integrations:          integrations.NewClient(opts...),
		SyncState:             syncstate.NewClient(opts...),
		WebhookEndpoints:      webhookendpoints.NewClient(opts...),
		PaymentIntents:        paymentintents.NewClient(opts...),
		Events:                events.NewClient(opts...),
		SubscriptionSchedules: subscriptionschedules.NewClient(opts...),
		TerminalPayments:      terminalpayments.NewClient(opts...),
		TerminalDevices:       terminaldevices.NewClient(opts...),
		Usage:                 usage.NewClient(opts...),
		Transactions:          transactions.NewClient(opts...),
		Exports:               exports.NewClient(opts...),
		Imports:               imports.NewClient(opts...),
	}
}
