// This file was auto-generated by Fern from our API Definition.

// Payout objects represent funds settled to your bank account from processed payments. Track settlement batches, reconcile amounts, and monitor payout timing across all payment gateways.
// 
// **Required Scopes:**
// - `payouts:read` - List and retrieve payouts
package payouts
