/*
RevKeen API

Testing CustomerMetersAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package revkeen

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/revkeen/revkeen-go"
)

func Test_revkeen_CustomerMetersAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CustomerMetersAPIService CustomerMetersGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var customerId string
		var meterId string

		resp, httpRes, err := apiClient.CustomerMetersAPI.CustomerMetersGet(context.Background(), customerId, meterId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CustomerMetersAPIService CustomerMetersList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CustomerMetersAPI.CustomerMetersList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
