// This file was auto-generated by Fern from our API Definition.

package revkeen

import (
	json "encoding/json"
	fmt "fmt"
	core "github.com/revkeen/revkeen-go/core"
	time "time"
)

type ChargesCaptureRequest struct {
	AmountMinor *int `json:"amountMinor,omitempty" url:"-"`
}

type ChargesCreateRequest struct {
	CustomerID          string                 `json:"customerId" url:"-"`
	AmountMinor         int                    `json:"amountMinor" url:"-"`
	Currency            *string                `json:"currency,omitempty" url:"-"`
	Description         string                 `json:"description" url:"-"`
	PaymentMethodID     *string                `json:"paymentMethodId,omitempty" url:"-"`
	Capture             *bool                  `json:"capture,omitempty" url:"-"`
	StatementDescriptor *string                `json:"statementDescriptor,omitempty" url:"-"`
	Metadata            map[string]interface{} `json:"metadata,omitempty" url:"-"`
	SendReceipt         *bool                  `json:"sendReceipt,omitempty" url:"-"`
	IdempotencyKey      *string                `json:"idempotencyKey,omitempty" url:"-"`
}

type ChargesListRequest struct {
	// Page number
	Page *int `json:"-" url:"page,omitempty"`
	// Maximum number of results (1-100)
	Limit *int `json:"-" url:"limit,omitempty"`
	// Filter by customer UUID
	CustomerID *string `json:"-" url:"customerId,omitempty"`
	// Filter by charge status
	Status *ChargesListRequestStatus `json:"-" url:"status,omitempty"`
	// Filter charges created on or after this date
	CreatedGte *time.Time `json:"-" url:"createdGte,omitempty"`
	// Filter charges created on or before this date
	CreatedLte *time.Time `json:"-" url:"createdLte,omitempty"`
}

type ChargesRefundRequest struct {
	AmountMinor *int                        `json:"amountMinor,omitempty" url:"-"`
	Reason      *ChargesRefundRequestReason `json:"reason,omitempty" url:"-"`
	Notes       *string                     `json:"notes,omitempty" url:"-"`
}

type ChargesRetrieveRequest struct {
}

// The charge object after capturing the authorized funds.
type ChargeCaptureResponse struct {
	Data *ChargeCaptureResponseData `json:"data,omitempty" url:"data,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *ChargeCaptureResponse) GetData() *ChargeCaptureResponseData {
	if c == nil {
		return nil
	}
	return c.Data
}

func (c *ChargeCaptureResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *ChargeCaptureResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ChargeCaptureResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ChargeCaptureResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *ChargeCaptureResponse) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type ChargeCaptureResponseData struct {
	ID                   string                          `json:"id" url:"id"`
	MerchantID           string                          `json:"merchantId" url:"merchantId"`
	CustomerID           string                          `json:"customerId" url:"customerId"`
	InvoiceID            *string                         `json:"invoiceId,omitempty" url:"invoiceId,omitempty"`
	PaymentMethodID      *string                         `json:"paymentMethodId,omitempty" url:"paymentMethodId,omitempty"`
	AmountMinor          int                             `json:"amountMinor" url:"amountMinor"`
	AmountCapturedMinor  int                             `json:"amountCapturedMinor" url:"amountCapturedMinor"`
	AmountRefundedMinor  int                             `json:"amountRefundedMinor" url:"amountRefundedMinor"`
	Currency             string                          `json:"currency" url:"currency"`
	Status               ChargeCaptureResponseDataStatus `json:"status" url:"status"`
	Description          string                          `json:"description" url:"description"`
	StatementDescriptor  *string                         `json:"statementDescriptor,omitempty" url:"statementDescriptor,omitempty"`
	FailureCode          *string                         `json:"failureCode,omitempty" url:"failureCode,omitempty"`
	FailureMessage       *string                         `json:"failureMessage,omitempty" url:"failureMessage,omitempty"`
	GatewayTransactionID *string                         `json:"gatewayTransactionId,omitempty" url:"gatewayTransactionId,omitempty"`
	ReceiptURL           *string                         `json:"receiptUrl,omitempty" url:"receiptUrl,omitempty"`
	Captured             bool                            `json:"captured" url:"captured"`
	Metadata             map[string]interface{}          `json:"metadata,omitempty" url:"metadata,omitempty"`
	CreatedAt            time.Time                       `json:"createdAt" url:"createdAt"`
	UpdatedAt            time.Time                       `json:"updatedAt" url:"updatedAt"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *ChargeCaptureResponseData) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *ChargeCaptureResponseData) GetMerchantID() string {
	if c == nil {
		return ""
	}
	return c.MerchantID
}

func (c *ChargeCaptureResponseData) GetCustomerID() string {
	if c == nil {
		return ""
	}
	return c.CustomerID
}

func (c *ChargeCaptureResponseData) GetInvoiceID() *string {
	if c == nil {
		return nil
	}
	return c.InvoiceID
}

func (c *ChargeCaptureResponseData) GetPaymentMethodID() *string {
	if c == nil {
		return nil
	}
	return c.PaymentMethodID
}

func (c *ChargeCaptureResponseData) GetAmountMinor() int {
	if c == nil {
		return 0
	}
	return c.AmountMinor
}

func (c *ChargeCaptureResponseData) GetAmountCapturedMinor() int {
	if c == nil {
		return 0
	}
	return c.AmountCapturedMinor
}

func (c *ChargeCaptureResponseData) GetAmountRefundedMinor() int {
	if c == nil {
		return 0
	}
	return c.AmountRefundedMinor
}

func (c *ChargeCaptureResponseData) GetCurrency() string {
	if c == nil {
		return ""
	}
	return c.Currency
}

func (c *ChargeCaptureResponseData) GetStatus() ChargeCaptureResponseDataStatus {
	if c == nil {
		return ""
	}
	return c.Status
}

func (c *ChargeCaptureResponseData) GetDescription() string {
	if c == nil {
		return ""
	}
	return c.Description
}

func (c *ChargeCaptureResponseData) GetStatementDescriptor() *string {
	if c == nil {
		return nil
	}
	return c.StatementDescriptor
}

func (c *ChargeCaptureResponseData) GetFailureCode() *string {
	if c == nil {
		return nil
	}
	return c.FailureCode
}

func (c *ChargeCaptureResponseData) GetFailureMessage() *string {
	if c == nil {
		return nil
	}
	return c.FailureMessage
}

func (c *ChargeCaptureResponseData) GetGatewayTransactionID() *string {
	if c == nil {
		return nil
	}
	return c.GatewayTransactionID
}

func (c *ChargeCaptureResponseData) GetReceiptURL() *string {
	if c == nil {
		return nil
	}
	return c.ReceiptURL
}

func (c *ChargeCaptureResponseData) GetCaptured() bool {
	if c == nil {
		return false
	}
	return c.Captured
}

func (c *ChargeCaptureResponseData) GetMetadata() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.Metadata
}

func (c *ChargeCaptureResponseData) GetCreatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreatedAt
}

func (c *ChargeCaptureResponseData) GetUpdatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.UpdatedAt
}

func (c *ChargeCaptureResponseData) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *ChargeCaptureResponseData) UnmarshalJSON(data []byte) error {
	type embed ChargeCaptureResponseData
	var unmarshaler = struct {
		embed
		CreatedAt *core.DateTime `json:"createdAt"`
		UpdatedAt *core.DateTime `json:"updatedAt"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = ChargeCaptureResponseData(unmarshaler.embed)
	c.CreatedAt = unmarshaler.CreatedAt.Time()
	c.UpdatedAt = unmarshaler.UpdatedAt.Time()

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *ChargeCaptureResponseData) MarshalJSON() ([]byte, error) {
	type embed ChargeCaptureResponseData
	var marshaler = struct {
		embed
		CreatedAt *core.DateTime `json:"createdAt"`
		UpdatedAt *core.DateTime `json:"updatedAt"`
	}{
		embed:     embed(*c),
		CreatedAt: core.NewDateTime(c.CreatedAt),
		UpdatedAt: core.NewDateTime(c.UpdatedAt),
	}
	return json.Marshal(marshaler)
}

func (c *ChargeCaptureResponseData) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type ChargeCaptureResponseDataStatus string

const (
	ChargeCaptureResponseDataStatusPending           ChargeCaptureResponseDataStatus = "pending"
	ChargeCaptureResponseDataStatusProcessing        ChargeCaptureResponseDataStatus = "processing"
	ChargeCaptureResponseDataStatusSucceeded         ChargeCaptureResponseDataStatus = "succeeded"
	ChargeCaptureResponseDataStatusFailed            ChargeCaptureResponseDataStatus = "failed"
	ChargeCaptureResponseDataStatusRefunded          ChargeCaptureResponseDataStatus = "refunded"
	ChargeCaptureResponseDataStatusPartiallyRefunded ChargeCaptureResponseDataStatus = "partially_refunded"
	ChargeCaptureResponseDataStatusVoided            ChargeCaptureResponseDataStatus = "voided"
)

func NewChargeCaptureResponseDataStatusFromString(s string) (ChargeCaptureResponseDataStatus, error) {
	switch s {
	case "pending":
		return ChargeCaptureResponseDataStatusPending, nil
	case "processing":
		return ChargeCaptureResponseDataStatusProcessing, nil
	case "succeeded":
		return ChargeCaptureResponseDataStatusSucceeded, nil
	case "failed":
		return ChargeCaptureResponseDataStatusFailed, nil
	case "refunded":
		return ChargeCaptureResponseDataStatusRefunded, nil
	case "partially_refunded":
		return ChargeCaptureResponseDataStatusPartiallyRefunded, nil
	case "voided":
		return ChargeCaptureResponseDataStatusVoided, nil
	}
	var t ChargeCaptureResponseDataStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c ChargeCaptureResponseDataStatus) Ptr() *ChargeCaptureResponseDataStatus {
	return &c
}

// The newly created charge object with gateway response details.
type ChargeCreateResponse struct {
	Data *ChargeCreateResponseData `json:"data,omitempty" url:"data,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *ChargeCreateResponse) GetData() *ChargeCreateResponseData {
	if c == nil {
		return nil
	}
	return c.Data
}

func (c *ChargeCreateResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *ChargeCreateResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ChargeCreateResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ChargeCreateResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *ChargeCreateResponse) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type ChargeCreateResponseData struct {
	ID                   string                         `json:"id" url:"id"`
	MerchantID           string                         `json:"merchantId" url:"merchantId"`
	CustomerID           string                         `json:"customerId" url:"customerId"`
	InvoiceID            *string                        `json:"invoiceId,omitempty" url:"invoiceId,omitempty"`
	PaymentMethodID      *string                        `json:"paymentMethodId,omitempty" url:"paymentMethodId,omitempty"`
	AmountMinor          int                            `json:"amountMinor" url:"amountMinor"`
	AmountCapturedMinor  int                            `json:"amountCapturedMinor" url:"amountCapturedMinor"`
	AmountRefundedMinor  int                            `json:"amountRefundedMinor" url:"amountRefundedMinor"`
	Currency             string                         `json:"currency" url:"currency"`
	Status               ChargeCreateResponseDataStatus `json:"status" url:"status"`
	Description          string                         `json:"description" url:"description"`
	StatementDescriptor  *string                        `json:"statementDescriptor,omitempty" url:"statementDescriptor,omitempty"`
	FailureCode          *string                        `json:"failureCode,omitempty" url:"failureCode,omitempty"`
	FailureMessage       *string                        `json:"failureMessage,omitempty" url:"failureMessage,omitempty"`
	GatewayTransactionID *string                        `json:"gatewayTransactionId,omitempty" url:"gatewayTransactionId,omitempty"`
	ReceiptURL           *string                        `json:"receiptUrl,omitempty" url:"receiptUrl,omitempty"`
	Captured             bool                           `json:"captured" url:"captured"`
	Metadata             map[string]interface{}         `json:"metadata,omitempty" url:"metadata,omitempty"`
	CreatedAt            time.Time                      `json:"createdAt" url:"createdAt"`
	UpdatedAt            time.Time                      `json:"updatedAt" url:"updatedAt"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *ChargeCreateResponseData) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *ChargeCreateResponseData) GetMerchantID() string {
	if c == nil {
		return ""
	}
	return c.MerchantID
}

func (c *ChargeCreateResponseData) GetCustomerID() string {
	if c == nil {
		return ""
	}
	return c.CustomerID
}

func (c *ChargeCreateResponseData) GetInvoiceID() *string {
	if c == nil {
		return nil
	}
	return c.InvoiceID
}

func (c *ChargeCreateResponseData) GetPaymentMethodID() *string {
	if c == nil {
		return nil
	}
	return c.PaymentMethodID
}

func (c *ChargeCreateResponseData) GetAmountMinor() int {
	if c == nil {
		return 0
	}
	return c.AmountMinor
}

func (c *ChargeCreateResponseData) GetAmountCapturedMinor() int {
	if c == nil {
		return 0
	}
	return c.AmountCapturedMinor
}

func (c *ChargeCreateResponseData) GetAmountRefundedMinor() int {
	if c == nil {
		return 0
	}
	return c.AmountRefundedMinor
}

func (c *ChargeCreateResponseData) GetCurrency() string {
	if c == nil {
		return ""
	}
	return c.Currency
}

func (c *ChargeCreateResponseData) GetStatus() ChargeCreateResponseDataStatus {
	if c == nil {
		return ""
	}
	return c.Status
}

func (c *ChargeCreateResponseData) GetDescription() string {
	if c == nil {
		return ""
	}
	return c.Description
}

func (c *ChargeCreateResponseData) GetStatementDescriptor() *string {
	if c == nil {
		return nil
	}
	return c.StatementDescriptor
}

func (c *ChargeCreateResponseData) GetFailureCode() *string {
	if c == nil {
		return nil
	}
	return c.FailureCode
}

func (c *ChargeCreateResponseData) GetFailureMessage() *string {
	if c == nil {
		return nil
	}
	return c.FailureMessage
}

func (c *ChargeCreateResponseData) GetGatewayTransactionID() *string {
	if c == nil {
		return nil
	}
	return c.GatewayTransactionID
}

func (c *ChargeCreateResponseData) GetReceiptURL() *string {
	if c == nil {
		return nil
	}
	return c.ReceiptURL
}

func (c *ChargeCreateResponseData) GetCaptured() bool {
	if c == nil {
		return false
	}
	return c.Captured
}

func (c *ChargeCreateResponseData) GetMetadata() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.Metadata
}

func (c *ChargeCreateResponseData) GetCreatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreatedAt
}

func (c *ChargeCreateResponseData) GetUpdatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.UpdatedAt
}

func (c *ChargeCreateResponseData) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *ChargeCreateResponseData) UnmarshalJSON(data []byte) error {
	type embed ChargeCreateResponseData
	var unmarshaler = struct {
		embed
		CreatedAt *core.DateTime `json:"createdAt"`
		UpdatedAt *core.DateTime `json:"updatedAt"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = ChargeCreateResponseData(unmarshaler.embed)
	c.CreatedAt = unmarshaler.CreatedAt.Time()
	c.UpdatedAt = unmarshaler.UpdatedAt.Time()

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *ChargeCreateResponseData) MarshalJSON() ([]byte, error) {
	type embed ChargeCreateResponseData
	var marshaler = struct {
		embed
		CreatedAt *core.DateTime `json:"createdAt"`
		UpdatedAt *core.DateTime `json:"updatedAt"`
	}{
		embed:     embed(*c),
		CreatedAt: core.NewDateTime(c.CreatedAt),
		UpdatedAt: core.NewDateTime(c.UpdatedAt),
	}
	return json.Marshal(marshaler)
}

func (c *ChargeCreateResponseData) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type ChargeCreateResponseDataStatus string

const (
	ChargeCreateResponseDataStatusPending           ChargeCreateResponseDataStatus = "pending"
	ChargeCreateResponseDataStatusProcessing        ChargeCreateResponseDataStatus = "processing"
	ChargeCreateResponseDataStatusSucceeded         ChargeCreateResponseDataStatus = "succeeded"
	ChargeCreateResponseDataStatusFailed            ChargeCreateResponseDataStatus = "failed"
	ChargeCreateResponseDataStatusRefunded          ChargeCreateResponseDataStatus = "refunded"
	ChargeCreateResponseDataStatusPartiallyRefunded ChargeCreateResponseDataStatus = "partially_refunded"
	ChargeCreateResponseDataStatusVoided            ChargeCreateResponseDataStatus = "voided"
)

func NewChargeCreateResponseDataStatusFromString(s string) (ChargeCreateResponseDataStatus, error) {
	switch s {
	case "pending":
		return ChargeCreateResponseDataStatusPending, nil
	case "processing":
		return ChargeCreateResponseDataStatusProcessing, nil
	case "succeeded":
		return ChargeCreateResponseDataStatusSucceeded, nil
	case "failed":
		return ChargeCreateResponseDataStatusFailed, nil
	case "refunded":
		return ChargeCreateResponseDataStatusRefunded, nil
	case "partially_refunded":
		return ChargeCreateResponseDataStatusPartiallyRefunded, nil
	case "voided":
		return ChargeCreateResponseDataStatusVoided, nil
	}
	var t ChargeCreateResponseDataStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c ChargeCreateResponseDataStatus) Ptr() *ChargeCreateResponseDataStatus {
	return &c
}

// A paginated list of charges matching the query filters.
type ChargeListResponse struct {
	Data       []*ChargeListResponseDataItem `json:"data,omitempty" url:"data,omitempty"`
	Pagination *ChargeListResponsePagination `json:"pagination,omitempty" url:"pagination,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *ChargeListResponse) GetData() []*ChargeListResponseDataItem {
	if c == nil {
		return nil
	}
	return c.Data
}

func (c *ChargeListResponse) GetPagination() *ChargeListResponsePagination {
	if c == nil {
		return nil
	}
	return c.Pagination
}

func (c *ChargeListResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *ChargeListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ChargeListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ChargeListResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *ChargeListResponse) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type ChargeListResponseDataItem struct {
	ID                   string                           `json:"id" url:"id"`
	MerchantID           string                           `json:"merchantId" url:"merchantId"`
	CustomerID           string                           `json:"customerId" url:"customerId"`
	InvoiceID            *string                          `json:"invoiceId,omitempty" url:"invoiceId,omitempty"`
	PaymentMethodID      *string                          `json:"paymentMethodId,omitempty" url:"paymentMethodId,omitempty"`
	AmountMinor          int                              `json:"amountMinor" url:"amountMinor"`
	AmountCapturedMinor  int                              `json:"amountCapturedMinor" url:"amountCapturedMinor"`
	AmountRefundedMinor  int                              `json:"amountRefundedMinor" url:"amountRefundedMinor"`
	Currency             string                           `json:"currency" url:"currency"`
	Status               ChargeListResponseDataItemStatus `json:"status" url:"status"`
	Description          string                           `json:"description" url:"description"`
	StatementDescriptor  *string                          `json:"statementDescriptor,omitempty" url:"statementDescriptor,omitempty"`
	FailureCode          *string                          `json:"failureCode,omitempty" url:"failureCode,omitempty"`
	FailureMessage       *string                          `json:"failureMessage,omitempty" url:"failureMessage,omitempty"`
	GatewayTransactionID *string                          `json:"gatewayTransactionId,omitempty" url:"gatewayTransactionId,omitempty"`
	ReceiptURL           *string                          `json:"receiptUrl,omitempty" url:"receiptUrl,omitempty"`
	Captured             bool                             `json:"captured" url:"captured"`
	Metadata             map[string]interface{}           `json:"metadata,omitempty" url:"metadata,omitempty"`
	CreatedAt            time.Time                        `json:"createdAt" url:"createdAt"`
	UpdatedAt            time.Time                        `json:"updatedAt" url:"updatedAt"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *ChargeListResponseDataItem) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *ChargeListResponseDataItem) GetMerchantID() string {
	if c == nil {
		return ""
	}
	return c.MerchantID
}

func (c *ChargeListResponseDataItem) GetCustomerID() string {
	if c == nil {
		return ""
	}
	return c.CustomerID
}

func (c *ChargeListResponseDataItem) GetInvoiceID() *string {
	if c == nil {
		return nil
	}
	return c.InvoiceID
}

func (c *ChargeListResponseDataItem) GetPaymentMethodID() *string {
	if c == nil {
		return nil
	}
	return c.PaymentMethodID
}

func (c *ChargeListResponseDataItem) GetAmountMinor() int {
	if c == nil {
		return 0
	}
	return c.AmountMinor
}

func (c *ChargeListResponseDataItem) GetAmountCapturedMinor() int {
	if c == nil {
		return 0
	}
	return c.AmountCapturedMinor
}

func (c *ChargeListResponseDataItem) GetAmountRefundedMinor() int {
	if c == nil {
		return 0
	}
	return c.AmountRefundedMinor
}

func (c *ChargeListResponseDataItem) GetCurrency() string {
	if c == nil {
		return ""
	}
	return c.Currency
}

func (c *ChargeListResponseDataItem) GetStatus() ChargeListResponseDataItemStatus {
	if c == nil {
		return ""
	}
	return c.Status
}

func (c *ChargeListResponseDataItem) GetDescription() string {
	if c == nil {
		return ""
	}
	return c.Description
}

func (c *ChargeListResponseDataItem) GetStatementDescriptor() *string {
	if c == nil {
		return nil
	}
	return c.StatementDescriptor
}

func (c *ChargeListResponseDataItem) GetFailureCode() *string {
	if c == nil {
		return nil
	}
	return c.FailureCode
}

func (c *ChargeListResponseDataItem) GetFailureMessage() *string {
	if c == nil {
		return nil
	}
	return c.FailureMessage
}

func (c *ChargeListResponseDataItem) GetGatewayTransactionID() *string {
	if c == nil {
		return nil
	}
	return c.GatewayTransactionID
}

func (c *ChargeListResponseDataItem) GetReceiptURL() *string {
	if c == nil {
		return nil
	}
	return c.ReceiptURL
}

func (c *ChargeListResponseDataItem) GetCaptured() bool {
	if c == nil {
		return false
	}
	return c.Captured
}

func (c *ChargeListResponseDataItem) GetMetadata() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.Metadata
}

func (c *ChargeListResponseDataItem) GetCreatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreatedAt
}

func (c *ChargeListResponseDataItem) GetUpdatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.UpdatedAt
}

func (c *ChargeListResponseDataItem) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *ChargeListResponseDataItem) UnmarshalJSON(data []byte) error {
	type embed ChargeListResponseDataItem
	var unmarshaler = struct {
		embed
		CreatedAt *core.DateTime `json:"createdAt"`
		UpdatedAt *core.DateTime `json:"updatedAt"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = ChargeListResponseDataItem(unmarshaler.embed)
	c.CreatedAt = unmarshaler.CreatedAt.Time()
	c.UpdatedAt = unmarshaler.UpdatedAt.Time()

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *ChargeListResponseDataItem) MarshalJSON() ([]byte, error) {
	type embed ChargeListResponseDataItem
	var marshaler = struct {
		embed
		CreatedAt *core.DateTime `json:"createdAt"`
		UpdatedAt *core.DateTime `json:"updatedAt"`
	}{
		embed:     embed(*c),
		CreatedAt: core.NewDateTime(c.CreatedAt),
		UpdatedAt: core.NewDateTime(c.UpdatedAt),
	}
	return json.Marshal(marshaler)
}

func (c *ChargeListResponseDataItem) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type ChargeListResponseDataItemStatus string

const (
	ChargeListResponseDataItemStatusPending           ChargeListResponseDataItemStatus = "pending"
	ChargeListResponseDataItemStatusProcessing        ChargeListResponseDataItemStatus = "processing"
	ChargeListResponseDataItemStatusSucceeded         ChargeListResponseDataItemStatus = "succeeded"
	ChargeListResponseDataItemStatusFailed            ChargeListResponseDataItemStatus = "failed"
	ChargeListResponseDataItemStatusRefunded          ChargeListResponseDataItemStatus = "refunded"
	ChargeListResponseDataItemStatusPartiallyRefunded ChargeListResponseDataItemStatus = "partially_refunded"
	ChargeListResponseDataItemStatusVoided            ChargeListResponseDataItemStatus = "voided"
)

func NewChargeListResponseDataItemStatusFromString(s string) (ChargeListResponseDataItemStatus, error) {
	switch s {
	case "pending":
		return ChargeListResponseDataItemStatusPending, nil
	case "processing":
		return ChargeListResponseDataItemStatusProcessing, nil
	case "succeeded":
		return ChargeListResponseDataItemStatusSucceeded, nil
	case "failed":
		return ChargeListResponseDataItemStatusFailed, nil
	case "refunded":
		return ChargeListResponseDataItemStatusRefunded, nil
	case "partially_refunded":
		return ChargeListResponseDataItemStatusPartiallyRefunded, nil
	case "voided":
		return ChargeListResponseDataItemStatusVoided, nil
	}
	var t ChargeListResponseDataItemStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c ChargeListResponseDataItemStatus) Ptr() *ChargeListResponseDataItemStatus {
	return &c
}

type ChargeListResponsePagination struct {
	// Current page number
	Page float64 `json:"page" url:"page"`
	// Maximum results per page
	Limit float64 `json:"limit" url:"limit"`
	// Total number of results matching the query
	Total float64 `json:"total" url:"total"`
	// Total number of pages available
	TotalPages float64 `json:"totalPages" url:"totalPages"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *ChargeListResponsePagination) GetPage() float64 {
	if c == nil {
		return 0
	}
	return c.Page
}

func (c *ChargeListResponsePagination) GetLimit() float64 {
	if c == nil {
		return 0
	}
	return c.Limit
}

func (c *ChargeListResponsePagination) GetTotal() float64 {
	if c == nil {
		return 0
	}
	return c.Total
}

func (c *ChargeListResponsePagination) GetTotalPages() float64 {
	if c == nil {
		return 0
	}
	return c.TotalPages
}

func (c *ChargeListResponsePagination) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *ChargeListResponsePagination) UnmarshalJSON(data []byte) error {
	type unmarshaler ChargeListResponsePagination
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ChargeListResponsePagination(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *ChargeListResponsePagination) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// The charge object after processing a full or partial refund.
type ChargeRefundResponse struct {
	Data *ChargeRefundResponseData `json:"data,omitempty" url:"data,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *ChargeRefundResponse) GetData() *ChargeRefundResponseData {
	if c == nil {
		return nil
	}
	return c.Data
}

func (c *ChargeRefundResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *ChargeRefundResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ChargeRefundResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ChargeRefundResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *ChargeRefundResponse) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type ChargeRefundResponseData struct {
	ID                   string                         `json:"id" url:"id"`
	MerchantID           string                         `json:"merchantId" url:"merchantId"`
	CustomerID           string                         `json:"customerId" url:"customerId"`
	InvoiceID            *string                        `json:"invoiceId,omitempty" url:"invoiceId,omitempty"`
	PaymentMethodID      *string                        `json:"paymentMethodId,omitempty" url:"paymentMethodId,omitempty"`
	AmountMinor          int                            `json:"amountMinor" url:"amountMinor"`
	AmountCapturedMinor  int                            `json:"amountCapturedMinor" url:"amountCapturedMinor"`
	AmountRefundedMinor  int                            `json:"amountRefundedMinor" url:"amountRefundedMinor"`
	Currency             string                         `json:"currency" url:"currency"`
	Status               ChargeRefundResponseDataStatus `json:"status" url:"status"`
	Description          string                         `json:"description" url:"description"`
	StatementDescriptor  *string                        `json:"statementDescriptor,omitempty" url:"statementDescriptor,omitempty"`
	FailureCode          *string                        `json:"failureCode,omitempty" url:"failureCode,omitempty"`
	FailureMessage       *string                        `json:"failureMessage,omitempty" url:"failureMessage,omitempty"`
	GatewayTransactionID *string                        `json:"gatewayTransactionId,omitempty" url:"gatewayTransactionId,omitempty"`
	ReceiptURL           *string                        `json:"receiptUrl,omitempty" url:"receiptUrl,omitempty"`
	Captured             bool                           `json:"captured" url:"captured"`
	Metadata             map[string]interface{}         `json:"metadata,omitempty" url:"metadata,omitempty"`
	CreatedAt            time.Time                      `json:"createdAt" url:"createdAt"`
	UpdatedAt            time.Time                      `json:"updatedAt" url:"updatedAt"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *ChargeRefundResponseData) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *ChargeRefundResponseData) GetMerchantID() string {
	if c == nil {
		return ""
	}
	return c.MerchantID
}

func (c *ChargeRefundResponseData) GetCustomerID() string {
	if c == nil {
		return ""
	}
	return c.CustomerID
}

func (c *ChargeRefundResponseData) GetInvoiceID() *string {
	if c == nil {
		return nil
	}
	return c.InvoiceID
}

func (c *ChargeRefundResponseData) GetPaymentMethodID() *string {
	if c == nil {
		return nil
	}
	return c.PaymentMethodID
}

func (c *ChargeRefundResponseData) GetAmountMinor() int {
	if c == nil {
		return 0
	}
	return c.AmountMinor
}

func (c *ChargeRefundResponseData) GetAmountCapturedMinor() int {
	if c == nil {
		return 0
	}
	return c.AmountCapturedMinor
}

func (c *ChargeRefundResponseData) GetAmountRefundedMinor() int {
	if c == nil {
		return 0
	}
	return c.AmountRefundedMinor
}

func (c *ChargeRefundResponseData) GetCurrency() string {
	if c == nil {
		return ""
	}
	return c.Currency
}

func (c *ChargeRefundResponseData) GetStatus() ChargeRefundResponseDataStatus {
	if c == nil {
		return ""
	}
	return c.Status
}

func (c *ChargeRefundResponseData) GetDescription() string {
	if c == nil {
		return ""
	}
	return c.Description
}

func (c *ChargeRefundResponseData) GetStatementDescriptor() *string {
	if c == nil {
		return nil
	}
	return c.StatementDescriptor
}

func (c *ChargeRefundResponseData) GetFailureCode() *string {
	if c == nil {
		return nil
	}
	return c.FailureCode
}

func (c *ChargeRefundResponseData) GetFailureMessage() *string {
	if c == nil {
		return nil
	}
	return c.FailureMessage
}

func (c *ChargeRefundResponseData) GetGatewayTransactionID() *string {
	if c == nil {
		return nil
	}
	return c.GatewayTransactionID
}

func (c *ChargeRefundResponseData) GetReceiptURL() *string {
	if c == nil {
		return nil
	}
	return c.ReceiptURL
}

func (c *ChargeRefundResponseData) GetCaptured() bool {
	if c == nil {
		return false
	}
	return c.Captured
}

func (c *ChargeRefundResponseData) GetMetadata() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.Metadata
}

func (c *ChargeRefundResponseData) GetCreatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreatedAt
}

func (c *ChargeRefundResponseData) GetUpdatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.UpdatedAt
}

func (c *ChargeRefundResponseData) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *ChargeRefundResponseData) UnmarshalJSON(data []byte) error {
	type embed ChargeRefundResponseData
	var unmarshaler = struct {
		embed
		CreatedAt *core.DateTime `json:"createdAt"`
		UpdatedAt *core.DateTime `json:"updatedAt"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = ChargeRefundResponseData(unmarshaler.embed)
	c.CreatedAt = unmarshaler.CreatedAt.Time()
	c.UpdatedAt = unmarshaler.UpdatedAt.Time()

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *ChargeRefundResponseData) MarshalJSON() ([]byte, error) {
	type embed ChargeRefundResponseData
	var marshaler = struct {
		embed
		CreatedAt *core.DateTime `json:"createdAt"`
		UpdatedAt *core.DateTime `json:"updatedAt"`
	}{
		embed:     embed(*c),
		CreatedAt: core.NewDateTime(c.CreatedAt),
		UpdatedAt: core.NewDateTime(c.UpdatedAt),
	}
	return json.Marshal(marshaler)
}

func (c *ChargeRefundResponseData) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type ChargeRefundResponseDataStatus string

const (
	ChargeRefundResponseDataStatusPending           ChargeRefundResponseDataStatus = "pending"
	ChargeRefundResponseDataStatusProcessing        ChargeRefundResponseDataStatus = "processing"
	ChargeRefundResponseDataStatusSucceeded         ChargeRefundResponseDataStatus = "succeeded"
	ChargeRefundResponseDataStatusFailed            ChargeRefundResponseDataStatus = "failed"
	ChargeRefundResponseDataStatusRefunded          ChargeRefundResponseDataStatus = "refunded"
	ChargeRefundResponseDataStatusPartiallyRefunded ChargeRefundResponseDataStatus = "partially_refunded"
	ChargeRefundResponseDataStatusVoided            ChargeRefundResponseDataStatus = "voided"
)

func NewChargeRefundResponseDataStatusFromString(s string) (ChargeRefundResponseDataStatus, error) {
	switch s {
	case "pending":
		return ChargeRefundResponseDataStatusPending, nil
	case "processing":
		return ChargeRefundResponseDataStatusProcessing, nil
	case "succeeded":
		return ChargeRefundResponseDataStatusSucceeded, nil
	case "failed":
		return ChargeRefundResponseDataStatusFailed, nil
	case "refunded":
		return ChargeRefundResponseDataStatusRefunded, nil
	case "partially_refunded":
		return ChargeRefundResponseDataStatusPartiallyRefunded, nil
	case "voided":
		return ChargeRefundResponseDataStatusVoided, nil
	}
	var t ChargeRefundResponseDataStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c ChargeRefundResponseDataStatus) Ptr() *ChargeRefundResponseDataStatus {
	return &c
}

// A single charge object with full details.
type ChargeRetrieveResponse struct {
	Data *ChargeRetrieveResponseData `json:"data,omitempty" url:"data,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *ChargeRetrieveResponse) GetData() *ChargeRetrieveResponseData {
	if c == nil {
		return nil
	}
	return c.Data
}

func (c *ChargeRetrieveResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *ChargeRetrieveResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ChargeRetrieveResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ChargeRetrieveResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *ChargeRetrieveResponse) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type ChargeRetrieveResponseData struct {
	ID                   string                           `json:"id" url:"id"`
	MerchantID           string                           `json:"merchantId" url:"merchantId"`
	CustomerID           string                           `json:"customerId" url:"customerId"`
	InvoiceID            *string                          `json:"invoiceId,omitempty" url:"invoiceId,omitempty"`
	PaymentMethodID      *string                          `json:"paymentMethodId,omitempty" url:"paymentMethodId,omitempty"`
	AmountMinor          int                              `json:"amountMinor" url:"amountMinor"`
	AmountCapturedMinor  int                              `json:"amountCapturedMinor" url:"amountCapturedMinor"`
	AmountRefundedMinor  int                              `json:"amountRefundedMinor" url:"amountRefundedMinor"`
	Currency             string                           `json:"currency" url:"currency"`
	Status               ChargeRetrieveResponseDataStatus `json:"status" url:"status"`
	Description          string                           `json:"description" url:"description"`
	StatementDescriptor  *string                          `json:"statementDescriptor,omitempty" url:"statementDescriptor,omitempty"`
	FailureCode          *string                          `json:"failureCode,omitempty" url:"failureCode,omitempty"`
	FailureMessage       *string                          `json:"failureMessage,omitempty" url:"failureMessage,omitempty"`
	GatewayTransactionID *string                          `json:"gatewayTransactionId,omitempty" url:"gatewayTransactionId,omitempty"`
	ReceiptURL           *string                          `json:"receiptUrl,omitempty" url:"receiptUrl,omitempty"`
	Captured             bool                             `json:"captured" url:"captured"`
	Metadata             map[string]interface{}           `json:"metadata,omitempty" url:"metadata,omitempty"`
	CreatedAt            time.Time                        `json:"createdAt" url:"createdAt"`
	UpdatedAt            time.Time                        `json:"updatedAt" url:"updatedAt"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *ChargeRetrieveResponseData) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *ChargeRetrieveResponseData) GetMerchantID() string {
	if c == nil {
		return ""
	}
	return c.MerchantID
}

func (c *ChargeRetrieveResponseData) GetCustomerID() string {
	if c == nil {
		return ""
	}
	return c.CustomerID
}

func (c *ChargeRetrieveResponseData) GetInvoiceID() *string {
	if c == nil {
		return nil
	}
	return c.InvoiceID
}

func (c *ChargeRetrieveResponseData) GetPaymentMethodID() *string {
	if c == nil {
		return nil
	}
	return c.PaymentMethodID
}

func (c *ChargeRetrieveResponseData) GetAmountMinor() int {
	if c == nil {
		return 0
	}
	return c.AmountMinor
}

func (c *ChargeRetrieveResponseData) GetAmountCapturedMinor() int {
	if c == nil {
		return 0
	}
	return c.AmountCapturedMinor
}

func (c *ChargeRetrieveResponseData) GetAmountRefundedMinor() int {
	if c == nil {
		return 0
	}
	return c.AmountRefundedMinor
}

func (c *ChargeRetrieveResponseData) GetCurrency() string {
	if c == nil {
		return ""
	}
	return c.Currency
}

func (c *ChargeRetrieveResponseData) GetStatus() ChargeRetrieveResponseDataStatus {
	if c == nil {
		return ""
	}
	return c.Status
}

func (c *ChargeRetrieveResponseData) GetDescription() string {
	if c == nil {
		return ""
	}
	return c.Description
}

func (c *ChargeRetrieveResponseData) GetStatementDescriptor() *string {
	if c == nil {
		return nil
	}
	return c.StatementDescriptor
}

func (c *ChargeRetrieveResponseData) GetFailureCode() *string {
	if c == nil {
		return nil
	}
	return c.FailureCode
}

func (c *ChargeRetrieveResponseData) GetFailureMessage() *string {
	if c == nil {
		return nil
	}
	return c.FailureMessage
}

func (c *ChargeRetrieveResponseData) GetGatewayTransactionID() *string {
	if c == nil {
		return nil
	}
	return c.GatewayTransactionID
}

func (c *ChargeRetrieveResponseData) GetReceiptURL() *string {
	if c == nil {
		return nil
	}
	return c.ReceiptURL
}

func (c *ChargeRetrieveResponseData) GetCaptured() bool {
	if c == nil {
		return false
	}
	return c.Captured
}

func (c *ChargeRetrieveResponseData) GetMetadata() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.Metadata
}

func (c *ChargeRetrieveResponseData) GetCreatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreatedAt
}

func (c *ChargeRetrieveResponseData) GetUpdatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.UpdatedAt
}

func (c *ChargeRetrieveResponseData) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *ChargeRetrieveResponseData) UnmarshalJSON(data []byte) error {
	type embed ChargeRetrieveResponseData
	var unmarshaler = struct {
		embed
		CreatedAt *core.DateTime `json:"createdAt"`
		UpdatedAt *core.DateTime `json:"updatedAt"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = ChargeRetrieveResponseData(unmarshaler.embed)
	c.CreatedAt = unmarshaler.CreatedAt.Time()
	c.UpdatedAt = unmarshaler.UpdatedAt.Time()

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *ChargeRetrieveResponseData) MarshalJSON() ([]byte, error) {
	type embed ChargeRetrieveResponseData
	var marshaler = struct {
		embed
		CreatedAt *core.DateTime `json:"createdAt"`
		UpdatedAt *core.DateTime `json:"updatedAt"`
	}{
		embed:     embed(*c),
		CreatedAt: core.NewDateTime(c.CreatedAt),
		UpdatedAt: core.NewDateTime(c.UpdatedAt),
	}
	return json.Marshal(marshaler)
}

func (c *ChargeRetrieveResponseData) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type ChargeRetrieveResponseDataStatus string

const (
	ChargeRetrieveResponseDataStatusPending           ChargeRetrieveResponseDataStatus = "pending"
	ChargeRetrieveResponseDataStatusProcessing        ChargeRetrieveResponseDataStatus = "processing"
	ChargeRetrieveResponseDataStatusSucceeded         ChargeRetrieveResponseDataStatus = "succeeded"
	ChargeRetrieveResponseDataStatusFailed            ChargeRetrieveResponseDataStatus = "failed"
	ChargeRetrieveResponseDataStatusRefunded          ChargeRetrieveResponseDataStatus = "refunded"
	ChargeRetrieveResponseDataStatusPartiallyRefunded ChargeRetrieveResponseDataStatus = "partially_refunded"
	ChargeRetrieveResponseDataStatusVoided            ChargeRetrieveResponseDataStatus = "voided"
)

func NewChargeRetrieveResponseDataStatusFromString(s string) (ChargeRetrieveResponseDataStatus, error) {
	switch s {
	case "pending":
		return ChargeRetrieveResponseDataStatusPending, nil
	case "processing":
		return ChargeRetrieveResponseDataStatusProcessing, nil
	case "succeeded":
		return ChargeRetrieveResponseDataStatusSucceeded, nil
	case "failed":
		return ChargeRetrieveResponseDataStatusFailed, nil
	case "refunded":
		return ChargeRetrieveResponseDataStatusRefunded, nil
	case "partially_refunded":
		return ChargeRetrieveResponseDataStatusPartiallyRefunded, nil
	case "voided":
		return ChargeRetrieveResponseDataStatusVoided, nil
	}
	var t ChargeRetrieveResponseDataStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c ChargeRetrieveResponseDataStatus) Ptr() *ChargeRetrieveResponseDataStatus {
	return &c
}

// Filter by charge status
type ChargesListRequestStatus string

const (
	ChargesListRequestStatusPending           ChargesListRequestStatus = "pending"
	ChargesListRequestStatusSucceeded         ChargesListRequestStatus = "succeeded"
	ChargesListRequestStatusFailed            ChargesListRequestStatus = "failed"
	ChargesListRequestStatusRefunded          ChargesListRequestStatus = "refunded"
	ChargesListRequestStatusPartiallyRefunded ChargesListRequestStatus = "partially_refunded"
)

func NewChargesListRequestStatusFromString(s string) (ChargesListRequestStatus, error) {
	switch s {
	case "pending":
		return ChargesListRequestStatusPending, nil
	case "succeeded":
		return ChargesListRequestStatusSucceeded, nil
	case "failed":
		return ChargesListRequestStatusFailed, nil
	case "refunded":
		return ChargesListRequestStatusRefunded, nil
	case "partially_refunded":
		return ChargesListRequestStatusPartiallyRefunded, nil
	}
	var t ChargesListRequestStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c ChargesListRequestStatus) Ptr() *ChargesListRequestStatus {
	return &c
}

type ChargesRefundRequestReason string

const (
	ChargesRefundRequestReasonDuplicate           ChargesRefundRequestReason = "duplicate"
	ChargesRefundRequestReasonFraudulent          ChargesRefundRequestReason = "fraudulent"
	ChargesRefundRequestReasonRequestedByCustomer ChargesRefundRequestReason = "requested_by_customer"
	ChargesRefundRequestReasonOther               ChargesRefundRequestReason = "other"
)

func NewChargesRefundRequestReasonFromString(s string) (ChargesRefundRequestReason, error) {
	switch s {
	case "duplicate":
		return ChargesRefundRequestReasonDuplicate, nil
	case "fraudulent":
		return ChargesRefundRequestReasonFraudulent, nil
	case "requested_by_customer":
		return ChargesRefundRequestReasonRequestedByCustomer, nil
	case "other":
		return ChargesRefundRequestReasonOther, nil
	}
	var t ChargesRefundRequestReason
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c ChargesRefundRequestReason) Ptr() *ChargesRefundRequestReason {
	return &c
}
