// This file was auto-generated by Fern from our API Definition.

package revkeen

import (
	json "encoding/json"
	fmt "fmt"
	core "github.com/revkeen/revkeen-go/core"
)

type CommsMessagesListRequest struct {
	// Maximum number of results (1-100)
	Limit *float64 `json:"-" url:"limit,omitempty"`
	// Number of results to skip
	Offset *float64 `json:"-" url:"offset,omitempty"`
}

type CommsMessagesSendRequest struct {
	CustomerID    *string                             `json:"customerId,omitempty" url:"-"`
	CustomerEmail *string                             `json:"customerEmail,omitempty" url:"-"`
	ThreadID      *string                             `json:"threadId,omitempty" url:"-"`
	Channel       CommsMessagesSendRequestChannel     `json:"channel" url:"-"`
	Subject       *string                             `json:"subject,omitempty" url:"-"`
	Body          string                              `json:"body" url:"-"`
	BodyHTML      *string                             `json:"bodyHtml,omitempty" url:"-"`
	EntityType    *CommsMessagesSendRequestEntityType `json:"entityType,omitempty" url:"-"`
	EntityID      *string                             `json:"entityId,omitempty" url:"-"`
	EntityURL     *string                             `json:"entityUrl,omitempty" url:"-"`
	Source        *CommsMessagesSendRequestSource     `json:"source,omitempty" url:"-"`
	// Custom key-value metadata
	Metadata map[string]interface{} `json:"metadata,omitempty" url:"-"`
}

type CommsThreadsListRequest struct {
	// Filter by customer UUID
	CustomerID *string `json:"-" url:"customerId,omitempty"`
	// Filter by thread status
	Status *CommsThreadsListRequestStatus `json:"-" url:"status,omitempty"`
	// Filter by channel
	Channel *string `json:"-" url:"channel,omitempty"`
	// Filter by related invoice UUID
	InvoiceID *string `json:"-" url:"invoiceId,omitempty"`
	// Maximum number of results (1-100)
	Limit *float64 `json:"-" url:"limit,omitempty"`
	// Number of results to skip
	Offset *float64 `json:"-" url:"offset,omitempty"`
}

type CommsMessagesListResponse struct {
	// Message objects
	Messages []map[string]interface{} `json:"messages,omitempty" url:"messages,omitempty"`
	Total    float64                  `json:"total" url:"total"`
	Limit    float64                  `json:"limit" url:"limit"`
	Offset   float64                  `json:"offset" url:"offset"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CommsMessagesListResponse) GetMessages() []map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.Messages
}

func (c *CommsMessagesListResponse) GetTotal() float64 {
	if c == nil {
		return 0
	}
	return c.Total
}

func (c *CommsMessagesListResponse) GetLimit() float64 {
	if c == nil {
		return 0
	}
	return c.Limit
}

func (c *CommsMessagesListResponse) GetOffset() float64 {
	if c == nil {
		return 0
	}
	return c.Offset
}

func (c *CommsMessagesListResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CommsMessagesListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CommsMessagesListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CommsMessagesListResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CommsMessagesListResponse) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CommsMessagesSendRequestChannel string

const (
	CommsMessagesSendRequestChannelEmail    CommsMessagesSendRequestChannel = "email"
	CommsMessagesSendRequestChannelSms      CommsMessagesSendRequestChannel = "sms"
	CommsMessagesSendRequestChannelWhatsapp CommsMessagesSendRequestChannel = "whatsapp"
)

func NewCommsMessagesSendRequestChannelFromString(s string) (CommsMessagesSendRequestChannel, error) {
	switch s {
	case "email":
		return CommsMessagesSendRequestChannelEmail, nil
	case "sms":
		return CommsMessagesSendRequestChannelSms, nil
	case "whatsapp":
		return CommsMessagesSendRequestChannelWhatsapp, nil
	}
	var t CommsMessagesSendRequestChannel
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CommsMessagesSendRequestChannel) Ptr() *CommsMessagesSendRequestChannel {
	return &c
}

type CommsMessagesSendRequestEntityType string

const (
	CommsMessagesSendRequestEntityTypeInvoice      CommsMessagesSendRequestEntityType = "invoice"
	CommsMessagesSendRequestEntityTypePaymentLink  CommsMessagesSendRequestEntityType = "payment_link"
	CommsMessagesSendRequestEntityTypePayment      CommsMessagesSendRequestEntityType = "payment"
	CommsMessagesSendRequestEntityTypeSubscription CommsMessagesSendRequestEntityType = "subscription"
)

func NewCommsMessagesSendRequestEntityTypeFromString(s string) (CommsMessagesSendRequestEntityType, error) {
	switch s {
	case "invoice":
		return CommsMessagesSendRequestEntityTypeInvoice, nil
	case "payment_link":
		return CommsMessagesSendRequestEntityTypePaymentLink, nil
	case "payment":
		return CommsMessagesSendRequestEntityTypePayment, nil
	case "subscription":
		return CommsMessagesSendRequestEntityTypeSubscription, nil
	}
	var t CommsMessagesSendRequestEntityType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CommsMessagesSendRequestEntityType) Ptr() *CommsMessagesSendRequestEntityType {
	return &c
}

type CommsMessagesSendRequestSource string

const (
	CommsMessagesSendRequestSourceSuperinbox CommsMessagesSendRequestSource = "superinbox"
	CommsMessagesSendRequestSourceExternal   CommsMessagesSendRequestSource = "external"
	CommsMessagesSendRequestSourceAPI        CommsMessagesSendRequestSource = "api"
	CommsMessagesSendRequestSourceAutomation CommsMessagesSendRequestSource = "automation"
)

func NewCommsMessagesSendRequestSourceFromString(s string) (CommsMessagesSendRequestSource, error) {
	switch s {
	case "superinbox":
		return CommsMessagesSendRequestSourceSuperinbox, nil
	case "external":
		return CommsMessagesSendRequestSourceExternal, nil
	case "api":
		return CommsMessagesSendRequestSourceAPI, nil
	case "automation":
		return CommsMessagesSendRequestSourceAutomation, nil
	}
	var t CommsMessagesSendRequestSource
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CommsMessagesSendRequestSource) Ptr() *CommsMessagesSendRequestSource {
	return &c
}

type CommsMessagesSendResponse struct {
	Success        bool   `json:"success" url:"success"`
	ConversationID string `json:"conversationId" url:"conversationId"`
	MessageID      string `json:"messageId" url:"messageId"`
	NotificationID string `json:"notificationId" url:"notificationId"`
	CustomerID     string `json:"customerId" url:"customerId"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CommsMessagesSendResponse) GetSuccess() bool {
	if c == nil {
		return false
	}
	return c.Success
}

func (c *CommsMessagesSendResponse) GetConversationID() string {
	if c == nil {
		return ""
	}
	return c.ConversationID
}

func (c *CommsMessagesSendResponse) GetMessageID() string {
	if c == nil {
		return ""
	}
	return c.MessageID
}

func (c *CommsMessagesSendResponse) GetNotificationID() string {
	if c == nil {
		return ""
	}
	return c.NotificationID
}

func (c *CommsMessagesSendResponse) GetCustomerID() string {
	if c == nil {
		return ""
	}
	return c.CustomerID
}

func (c *CommsMessagesSendResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CommsMessagesSendResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CommsMessagesSendResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CommsMessagesSendResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CommsMessagesSendResponse) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Filter by thread status
type CommsThreadsListRequestStatus string

const (
	CommsThreadsListRequestStatusOpen    CommsThreadsListRequestStatus = "open"
	CommsThreadsListRequestStatusClosed  CommsThreadsListRequestStatus = "closed"
	CommsThreadsListRequestStatusPending CommsThreadsListRequestStatus = "pending"
)

func NewCommsThreadsListRequestStatusFromString(s string) (CommsThreadsListRequestStatus, error) {
	switch s {
	case "open":
		return CommsThreadsListRequestStatusOpen, nil
	case "closed":
		return CommsThreadsListRequestStatusClosed, nil
	case "pending":
		return CommsThreadsListRequestStatusPending, nil
	}
	var t CommsThreadsListRequestStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CommsThreadsListRequestStatus) Ptr() *CommsThreadsListRequestStatus {
	return &c
}

type CommsThreadsListResponse struct {
	// Thread objects
	Threads []map[string]interface{} `json:"threads,omitempty" url:"threads,omitempty"`
	Total   float64                  `json:"total" url:"total"`
	Limit   float64                  `json:"limit" url:"limit"`
	Offset  float64                  `json:"offset" url:"offset"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CommsThreadsListResponse) GetThreads() []map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.Threads
}

func (c *CommsThreadsListResponse) GetTotal() float64 {
	if c == nil {
		return 0
	}
	return c.Total
}

func (c *CommsThreadsListResponse) GetLimit() float64 {
	if c == nil {
		return 0
	}
	return c.Limit
}

func (c *CommsThreadsListResponse) GetOffset() float64 {
	if c == nil {
		return 0
	}
	return c.Offset
}

func (c *CommsThreadsListResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CommsThreadsListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CommsThreadsListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CommsThreadsListResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CommsThreadsListResponse) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}
