// This file was auto-generated by Fern from our API Definition.

package revkeen

import (
	json "encoding/json"
	fmt "fmt"
	core "github.com/revkeen/revkeen-go/core"
)

type CreateCreditNoteInput struct {
	// The ID of the invoice to issue a credit note for
	InvoiceID string `json:"invoice_id" url:"-"`
	// Amount to credit in cents
	AmountMinor float64 `json:"amount_minor" url:"-"`
	// Tax portion of the credit in cents (for UK/EU VAT compliance)
	TaxAmountMinor *float64 `json:"tax_amount_minor,omitempty" url:"-"`
	// How the credit should be applied
	CreditMethod *CreateCreditNoteInputCreditMethod `json:"credit_method,omitempty" url:"-"`
	// Reason for the credit note
	Reason *string `json:"reason,omitempty" url:"-"`
	// Standardized reason code
	ReasonCode *CreateCreditNoteInputReasonCode `json:"reason_code,omitempty" url:"-"`
	// Whether to cancel the associated subscription after issuing
	CancelSubscription *bool `json:"cancel_subscription,omitempty" url:"-"`
	// Whether this credit note represents a prorated amount
	IsProrated *bool `json:"is_prorated,omitempty" url:"-"`
	// Total days in the billing period (for prorated credits)
	ProrationDaysTotal *float64 `json:"proration_days_total,omitempty" url:"-"`
	// Unused days in the billing period (for prorated credits)
	ProrationDaysUnused *float64 `json:"proration_days_unused,omitempty" url:"-"`
	// Idempotency key to prevent duplicate credit notes
	IdempotencyKey *string `json:"idempotency_key,omitempty" url:"-"`
	// Arbitrary key-value metadata
	Metadata map[string]interface{} `json:"metadata,omitempty" url:"-"`
	// When true, automatically trigger the process-credit-note task for multi-gateway reversal routing. Response will include gateway_operations array.
	AutoRoute *bool `json:"auto_route,omitempty" url:"-"`
	// For terminal (card-present) transactions: whether the customer is physically at the terminal. Defaults to false in API context.
	CustomerPresent *bool `json:"customer_present,omitempty" url:"-"`
}

type CreditNotesInvoiceEligibilityRequest struct {
}

type CreditNotesListRequest struct {
	// Filter by credit note status
	Status *CreditNotesListRequestStatus `json:"-" url:"status,omitempty"`
	// Filter by invoice ID
	InvoiceID *string `json:"-" url:"invoice_id,omitempty"`
	// Filter by customer ID
	CustomerID *string `json:"-" url:"customer_id,omitempty"`
	// Filter by credit method
	CreditMethod *CreditNotesListRequestCreditMethod `json:"-" url:"credit_method,omitempty"`
	// ISO 8601 date - only credit notes created after this date
	CreatedAfter *string `json:"-" url:"created_after,omitempty"`
	// ISO 8601 date - only credit notes created before this date
	CreatedBefore *string `json:"-" url:"created_before,omitempty"`
	// Number of results to return (1-100)
	Limit *float64 `json:"-" url:"limit,omitempty"`
	// Number of results to skip
	Offset *float64 `json:"-" url:"offset,omitempty"`
}

type CreditNotesRetrieveRequest struct {
}

type CreditNotesTransactionReversalEligibilityRequest struct {
	// Whether the customer is physically present at the terminal. Enables terminal-native reversal operations.
	CustomerPresent *bool `json:"-" url:"customer_present,omitempty"`
}

// The newly created credit note with issued status and PDF URL.
type CreditNoteCreateResponse struct {
	Data *CreditNote `json:"data,omitempty" url:"data,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CreditNoteCreateResponse) GetData() *CreditNote {
	if c == nil {
		return nil
	}
	return c.Data
}

func (c *CreditNoteCreateResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreditNoteCreateResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CreditNoteCreateResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreditNoteCreateResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreditNoteCreateResponse) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Eligibility details showing whether a credit note can be issued for the specified invoice and the maximum creditable amount.
type CreditNoteEligibilityResponse struct {
	InvoiceID          string                                       `json:"invoice_id" url:"invoice_id"`
	TotalAmountMinor   float64                                      `json:"total_amount_minor" url:"total_amount_minor"`
	TotalPaidMinor     float64                                      `json:"total_paid_minor" url:"total_paid_minor"`
	TotalCreditedMinor float64                                      `json:"total_credited_minor" url:"total_credited_minor"`
	MaxCreditableMinor float64                                      `json:"max_creditable_minor" url:"max_creditable_minor"`
	Eligible           bool                                         `json:"eligible" url:"eligible"`
	Payments           []*CreditNoteEligibilityResponsePaymentsItem `json:"payments,omitempty" url:"payments,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CreditNoteEligibilityResponse) GetInvoiceID() string {
	if c == nil {
		return ""
	}
	return c.InvoiceID
}

func (c *CreditNoteEligibilityResponse) GetTotalAmountMinor() float64 {
	if c == nil {
		return 0
	}
	return c.TotalAmountMinor
}

func (c *CreditNoteEligibilityResponse) GetTotalPaidMinor() float64 {
	if c == nil {
		return 0
	}
	return c.TotalPaidMinor
}

func (c *CreditNoteEligibilityResponse) GetTotalCreditedMinor() float64 {
	if c == nil {
		return 0
	}
	return c.TotalCreditedMinor
}

func (c *CreditNoteEligibilityResponse) GetMaxCreditableMinor() float64 {
	if c == nil {
		return 0
	}
	return c.MaxCreditableMinor
}

func (c *CreditNoteEligibilityResponse) GetEligible() bool {
	if c == nil {
		return false
	}
	return c.Eligible
}

func (c *CreditNoteEligibilityResponse) GetPayments() []*CreditNoteEligibilityResponsePaymentsItem {
	if c == nil {
		return nil
	}
	return c.Payments
}

func (c *CreditNoteEligibilityResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreditNoteEligibilityResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CreditNoteEligibilityResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreditNoteEligibilityResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreditNoteEligibilityResponse) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CreditNoteEligibilityResponsePaymentsItem struct {
	TransactionID        string                                                `json:"transaction_id" url:"transaction_id"`
	Gateway              string                                                `json:"gateway" url:"gateway"`
	PaymentMethod        *string                                               `json:"payment_method,omitempty" url:"payment_method,omitempty"`
	AmountMinor          float64                                               `json:"amount_minor" url:"amount_minor"`
	AmountRefundedMinor  float64                                               `json:"amount_refunded_minor" url:"amount_refunded_minor"`
	AmountAvailableMinor float64                                               `json:"amount_available_minor" url:"amount_available_minor"`
	CardBrand            *string                                               `json:"card_brand,omitempty" url:"card_brand,omitempty"`
	CardLast4            *string                                               `json:"card_last4,omitempty" url:"card_last4,omitempty"`
	TerminalSerial       *string                                               `json:"terminal_serial,omitempty" url:"terminal_serial,omitempty"`
	AvailableOperations  []string                                              `json:"available_operations,omitempty" url:"available_operations,omitempty"`
	Constraints          *CreditNoteEligibilityResponsePaymentsItemConstraints `json:"constraints,omitempty" url:"constraints,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CreditNoteEligibilityResponsePaymentsItem) GetTransactionID() string {
	if c == nil {
		return ""
	}
	return c.TransactionID
}

func (c *CreditNoteEligibilityResponsePaymentsItem) GetGateway() string {
	if c == nil {
		return ""
	}
	return c.Gateway
}

func (c *CreditNoteEligibilityResponsePaymentsItem) GetPaymentMethod() *string {
	if c == nil {
		return nil
	}
	return c.PaymentMethod
}

func (c *CreditNoteEligibilityResponsePaymentsItem) GetAmountMinor() float64 {
	if c == nil {
		return 0
	}
	return c.AmountMinor
}

func (c *CreditNoteEligibilityResponsePaymentsItem) GetAmountRefundedMinor() float64 {
	if c == nil {
		return 0
	}
	return c.AmountRefundedMinor
}

func (c *CreditNoteEligibilityResponsePaymentsItem) GetAmountAvailableMinor() float64 {
	if c == nil {
		return 0
	}
	return c.AmountAvailableMinor
}

func (c *CreditNoteEligibilityResponsePaymentsItem) GetCardBrand() *string {
	if c == nil {
		return nil
	}
	return c.CardBrand
}

func (c *CreditNoteEligibilityResponsePaymentsItem) GetCardLast4() *string {
	if c == nil {
		return nil
	}
	return c.CardLast4
}

func (c *CreditNoteEligibilityResponsePaymentsItem) GetTerminalSerial() *string {
	if c == nil {
		return nil
	}
	return c.TerminalSerial
}

func (c *CreditNoteEligibilityResponsePaymentsItem) GetAvailableOperations() []string {
	if c == nil {
		return nil
	}
	return c.AvailableOperations
}

func (c *CreditNoteEligibilityResponsePaymentsItem) GetConstraints() *CreditNoteEligibilityResponsePaymentsItemConstraints {
	if c == nil {
		return nil
	}
	return c.Constraints
}

func (c *CreditNoteEligibilityResponsePaymentsItem) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreditNoteEligibilityResponsePaymentsItem) UnmarshalJSON(data []byte) error {
	type unmarshaler CreditNoteEligibilityResponsePaymentsItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreditNoteEligibilityResponsePaymentsItem(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreditNoteEligibilityResponsePaymentsItem) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CreditNoteEligibilityResponsePaymentsItemConstraints struct {
	PartialSupported       bool `json:"partial_supported" url:"partial_supported"`
	RequiresCardPresent    bool `json:"requires_card_present" url:"requires_card_present"`
	RequiresTerminalOnline bool `json:"requires_terminal_online" url:"requires_terminal_online"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CreditNoteEligibilityResponsePaymentsItemConstraints) GetPartialSupported() bool {
	if c == nil {
		return false
	}
	return c.PartialSupported
}

func (c *CreditNoteEligibilityResponsePaymentsItemConstraints) GetRequiresCardPresent() bool {
	if c == nil {
		return false
	}
	return c.RequiresCardPresent
}

func (c *CreditNoteEligibilityResponsePaymentsItemConstraints) GetRequiresTerminalOnline() bool {
	if c == nil {
		return false
	}
	return c.RequiresTerminalOnline
}

func (c *CreditNoteEligibilityResponsePaymentsItemConstraints) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreditNoteEligibilityResponsePaymentsItemConstraints) UnmarshalJSON(data []byte) error {
	type unmarshaler CreditNoteEligibilityResponsePaymentsItemConstraints
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreditNoteEligibilityResponsePaymentsItemConstraints(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreditNoteEligibilityResponsePaymentsItemConstraints) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// A single credit note with full details including the associated invoice and refund.
type CreditNoteRetrieveResponse struct {
	Data *CreditNote `json:"data,omitempty" url:"data,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CreditNoteRetrieveResponse) GetData() *CreditNote {
	if c == nil {
		return nil
	}
	return c.Data
}

func (c *CreditNoteRetrieveResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreditNoteRetrieveResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CreditNoteRetrieveResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreditNoteRetrieveResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreditNoteRetrieveResponse) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// The credit note after being voided, reversing its accounting effect.
type CreditNoteVoidResponse struct {
	Data *CreditNote `json:"data,omitempty" url:"data,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CreditNoteVoidResponse) GetData() *CreditNote {
	if c == nil {
		return nil
	}
	return c.Data
}

func (c *CreditNoteVoidResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreditNoteVoidResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CreditNoteVoidResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreditNoteVoidResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreditNoteVoidResponse) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Details about which reversal methods (refund, void, or credit note) are available for a specific transaction.
type TransactionReversalEligibilityResponse struct {
	CanReverse          bool                                               `json:"can_reverse" url:"can_reverse"`
	TransactionID       string                                             `json:"transaction_id" url:"transaction_id"`
	Gateway             string                                             `json:"gateway" url:"gateway"`
	PaymentMethod       *string                                            `json:"payment_method,omitempty" url:"payment_method,omitempty"`
	AvailableOperations []string                                           `json:"available_operations,omitempty" url:"available_operations,omitempty"`
	Constraints         *TransactionReversalEligibilityResponseConstraints `json:"constraints,omitempty" url:"constraints,omitempty"`
	CardBrand           *string                                            `json:"card_brand,omitempty" url:"card_brand,omitempty"`
	CardLast4           *string                                            `json:"card_last4,omitempty" url:"card_last4,omitempty"`
	TerminalSerial      *string                                            `json:"terminal_serial,omitempty" url:"terminal_serial,omitempty"`
	TerminalUti         *string                                            `json:"terminal_uti,omitempty" url:"terminal_uti,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (t *TransactionReversalEligibilityResponse) GetCanReverse() bool {
	if t == nil {
		return false
	}
	return t.CanReverse
}

func (t *TransactionReversalEligibilityResponse) GetTransactionID() string {
	if t == nil {
		return ""
	}
	return t.TransactionID
}

func (t *TransactionReversalEligibilityResponse) GetGateway() string {
	if t == nil {
		return ""
	}
	return t.Gateway
}

func (t *TransactionReversalEligibilityResponse) GetPaymentMethod() *string {
	if t == nil {
		return nil
	}
	return t.PaymentMethod
}

func (t *TransactionReversalEligibilityResponse) GetAvailableOperations() []string {
	if t == nil {
		return nil
	}
	return t.AvailableOperations
}

func (t *TransactionReversalEligibilityResponse) GetConstraints() *TransactionReversalEligibilityResponseConstraints {
	if t == nil {
		return nil
	}
	return t.Constraints
}

func (t *TransactionReversalEligibilityResponse) GetCardBrand() *string {
	if t == nil {
		return nil
	}
	return t.CardBrand
}

func (t *TransactionReversalEligibilityResponse) GetCardLast4() *string {
	if t == nil {
		return nil
	}
	return t.CardLast4
}

func (t *TransactionReversalEligibilityResponse) GetTerminalSerial() *string {
	if t == nil {
		return nil
	}
	return t.TerminalSerial
}

func (t *TransactionReversalEligibilityResponse) GetTerminalUti() *string {
	if t == nil {
		return nil
	}
	return t.TerminalUti
}

func (t *TransactionReversalEligibilityResponse) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TransactionReversalEligibilityResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler TransactionReversalEligibilityResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TransactionReversalEligibilityResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties

	t._rawJSON = json.RawMessage(data)
	return nil
}

func (t *TransactionReversalEligibilityResponse) String() string {
	if len(t._rawJSON) > 0 {
		if value, err := core.StringifyJSON(t._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

type TransactionReversalEligibilityResponseConstraints struct {
	MaxAmount              float64 `json:"max_amount" url:"max_amount"`
	PartialSupported       bool    `json:"partial_supported" url:"partial_supported"`
	RequiresCardPresent    bool    `json:"requires_card_present" url:"requires_card_present"`
	RequiresTerminalOnline bool    `json:"requires_terminal_online" url:"requires_terminal_online"`
	RequiresCustomerIban   bool    `json:"requires_customer_iban" url:"requires_customer_iban"`
	Reason                 *string `json:"reason,omitempty" url:"reason,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (t *TransactionReversalEligibilityResponseConstraints) GetMaxAmount() float64 {
	if t == nil {
		return 0
	}
	return t.MaxAmount
}

func (t *TransactionReversalEligibilityResponseConstraints) GetPartialSupported() bool {
	if t == nil {
		return false
	}
	return t.PartialSupported
}

func (t *TransactionReversalEligibilityResponseConstraints) GetRequiresCardPresent() bool {
	if t == nil {
		return false
	}
	return t.RequiresCardPresent
}

func (t *TransactionReversalEligibilityResponseConstraints) GetRequiresTerminalOnline() bool {
	if t == nil {
		return false
	}
	return t.RequiresTerminalOnline
}

func (t *TransactionReversalEligibilityResponseConstraints) GetRequiresCustomerIban() bool {
	if t == nil {
		return false
	}
	return t.RequiresCustomerIban
}

func (t *TransactionReversalEligibilityResponseConstraints) GetReason() *string {
	if t == nil {
		return nil
	}
	return t.Reason
}

func (t *TransactionReversalEligibilityResponseConstraints) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TransactionReversalEligibilityResponseConstraints) UnmarshalJSON(data []byte) error {
	type unmarshaler TransactionReversalEligibilityResponseConstraints
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TransactionReversalEligibilityResponseConstraints(value)

	extraProperties, err := core.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties

	t._rawJSON = json.RawMessage(data)
	return nil
}

func (t *TransactionReversalEligibilityResponseConstraints) String() string {
	if len(t._rawJSON) > 0 {
		if value, err := core.StringifyJSON(t._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

// How the credit should be applied
type CreateCreditNoteInputCreditMethod string

const (
	CreateCreditNoteInputCreditMethodRefundToPaymentMethod CreateCreditNoteInputCreditMethod = "refund_to_payment_method"
	CreateCreditNoteInputCreditMethodCustomerBalance       CreateCreditNoteInputCreditMethod = "customer_balance"
	CreateCreditNoteInputCreditMethodExternal              CreateCreditNoteInputCreditMethod = "external"
)

func NewCreateCreditNoteInputCreditMethodFromString(s string) (CreateCreditNoteInputCreditMethod, error) {
	switch s {
	case "refund_to_payment_method":
		return CreateCreditNoteInputCreditMethodRefundToPaymentMethod, nil
	case "customer_balance":
		return CreateCreditNoteInputCreditMethodCustomerBalance, nil
	case "external":
		return CreateCreditNoteInputCreditMethodExternal, nil
	}
	var t CreateCreditNoteInputCreditMethod
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateCreditNoteInputCreditMethod) Ptr() *CreateCreditNoteInputCreditMethod {
	return &c
}

// Standardized reason code
type CreateCreditNoteInputReasonCode string

const (
	CreateCreditNoteInputReasonCodeCustomerRequest          CreateCreditNoteInputReasonCode = "customer_request"
	CreateCreditNoteInputReasonCodeDuplicateCharge          CreateCreditNoteInputReasonCode = "duplicate_charge"
	CreateCreditNoteInputReasonCodeServiceIssue             CreateCreditNoteInputReasonCode = "service_issue"
	CreateCreditNoteInputReasonCodeBillingError             CreateCreditNoteInputReasonCode = "billing_error"
	CreateCreditNoteInputReasonCodeSubscriptionCancellation CreateCreditNoteInputReasonCode = "subscription_cancellation"
	CreateCreditNoteInputReasonCodeProration                CreateCreditNoteInputReasonCode = "proration"
	CreateCreditNoteInputReasonCodeOther                    CreateCreditNoteInputReasonCode = "other"
)

func NewCreateCreditNoteInputReasonCodeFromString(s string) (CreateCreditNoteInputReasonCode, error) {
	switch s {
	case "customer_request":
		return CreateCreditNoteInputReasonCodeCustomerRequest, nil
	case "duplicate_charge":
		return CreateCreditNoteInputReasonCodeDuplicateCharge, nil
	case "service_issue":
		return CreateCreditNoteInputReasonCodeServiceIssue, nil
	case "billing_error":
		return CreateCreditNoteInputReasonCodeBillingError, nil
	case "subscription_cancellation":
		return CreateCreditNoteInputReasonCodeSubscriptionCancellation, nil
	case "proration":
		return CreateCreditNoteInputReasonCodeProration, nil
	case "other":
		return CreateCreditNoteInputReasonCodeOther, nil
	}
	var t CreateCreditNoteInputReasonCode
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateCreditNoteInputReasonCode) Ptr() *CreateCreditNoteInputReasonCode {
	return &c
}

type CreditNotesInvoiceEligibilityResponse struct {
	Data *CreditNoteEligibilityResponse `json:"data,omitempty" url:"data,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CreditNotesInvoiceEligibilityResponse) GetData() *CreditNoteEligibilityResponse {
	if c == nil {
		return nil
	}
	return c.Data
}

func (c *CreditNotesInvoiceEligibilityResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreditNotesInvoiceEligibilityResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CreditNotesInvoiceEligibilityResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreditNotesInvoiceEligibilityResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreditNotesInvoiceEligibilityResponse) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Filter by credit method
type CreditNotesListRequestCreditMethod string

const (
	CreditNotesListRequestCreditMethodRefundToPaymentMethod CreditNotesListRequestCreditMethod = "refund_to_payment_method"
	CreditNotesListRequestCreditMethodCustomerBalance       CreditNotesListRequestCreditMethod = "customer_balance"
	CreditNotesListRequestCreditMethodExternal              CreditNotesListRequestCreditMethod = "external"
)

func NewCreditNotesListRequestCreditMethodFromString(s string) (CreditNotesListRequestCreditMethod, error) {
	switch s {
	case "refund_to_payment_method":
		return CreditNotesListRequestCreditMethodRefundToPaymentMethod, nil
	case "customer_balance":
		return CreditNotesListRequestCreditMethodCustomerBalance, nil
	case "external":
		return CreditNotesListRequestCreditMethodExternal, nil
	}
	var t CreditNotesListRequestCreditMethod
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreditNotesListRequestCreditMethod) Ptr() *CreditNotesListRequestCreditMethod {
	return &c
}

// Filter by credit note status
type CreditNotesListRequestStatus string

const (
	CreditNotesListRequestStatusDraft   CreditNotesListRequestStatus = "draft"
	CreditNotesListRequestStatusPending CreditNotesListRequestStatus = "pending"
	CreditNotesListRequestStatusIssued  CreditNotesListRequestStatus = "issued"
	CreditNotesListRequestStatusApplied CreditNotesListRequestStatus = "applied"
	CreditNotesListRequestStatusVoided  CreditNotesListRequestStatus = "voided"
)

func NewCreditNotesListRequestStatusFromString(s string) (CreditNotesListRequestStatus, error) {
	switch s {
	case "draft":
		return CreditNotesListRequestStatusDraft, nil
	case "pending":
		return CreditNotesListRequestStatusPending, nil
	case "issued":
		return CreditNotesListRequestStatusIssued, nil
	case "applied":
		return CreditNotesListRequestStatusApplied, nil
	case "voided":
		return CreditNotesListRequestStatusVoided, nil
	}
	var t CreditNotesListRequestStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreditNotesListRequestStatus) Ptr() *CreditNotesListRequestStatus {
	return &c
}

type CreditNotesTransactionReversalEligibilityResponse struct {
	Data *TransactionReversalEligibilityResponse `json:"data,omitempty" url:"data,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CreditNotesTransactionReversalEligibilityResponse) GetData() *TransactionReversalEligibilityResponse {
	if c == nil {
		return nil
	}
	return c.Data
}

func (c *CreditNotesTransactionReversalEligibilityResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreditNotesTransactionReversalEligibilityResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CreditNotesTransactionReversalEligibilityResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreditNotesTransactionReversalEligibilityResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreditNotesTransactionReversalEligibilityResponse) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CreditNotesVoidRequest struct {
}
