// This file was auto-generated by Fern from our API Definition.

package revkeen

import (
	json "encoding/json"
	fmt "fmt"
	core "github.com/revkeen/revkeen-go/core"
	time "time"
)

type CreateImportRequest struct {
	// The type of resource to import.
	ResourceType CreateImportRequestResourceType `json:"resource_type" url:"-"`
	// URL to the CSV file to import (if not using multipart upload)
	FileURL *string `json:"file_url,omitempty" url:"-"`
	// Map CSV column names to resource fields (e.g., { 'Email Address': 'email', 'Full Name': 'name' })
	ColumnMapping map[string]interface{} `json:"column_mapping,omitempty" url:"-"`
	// Behavior when a duplicate record is found. skip: ignore the row. update: merge new data. error: fail the row.
	OnDuplicate *CreateImportRequestOnDuplicate `json:"on_duplicate,omitempty" url:"-"`
}

type ImportsRetrieveRequest struct {
}

// An async data import job. Upload a CSV file to create records in bulk. Poll GET /v2/imports/:id for status and error details.
type Import struct {
	// Unique import job ID
	ID string `json:"id" url:"id"`
	// Object type
	Object ImportObject `json:"object" url:"object"`
	// Import job status. pending: queued. validating: checking data. processing: creating records. completed: all rows imported. completed_with_errors: some rows failed. failed: import aborted.
	Status ImportStatus `json:"status" url:"status"`
	// The type of resource to import.
	ResourceType ImportResourceType `json:"resource_type" url:"resource_type"`
	// Total rows in the uploaded file
	TotalRows *int `json:"total_rows,omitempty" url:"total_rows,omitempty"`
	// Number of rows processed so far
	ProcessedRows *int `json:"processed_rows,omitempty" url:"processed_rows,omitempty"`
	// Number of rows successfully imported
	SuccessCount *int `json:"success_count,omitempty" url:"success_count,omitempty"`
	// Number of rows that failed
	ErrorCount *int `json:"error_count,omitempty" url:"error_count,omitempty"`
	// Detailed error information for failed rows
	Errors []*ImportErrorsItem `json:"errors,omitempty" url:"errors,omitempty"`
	// When the import was created (ISO 8601)
	CreatedAt time.Time `json:"created_at" url:"created_at"`
	// When the import completed (ISO 8601)
	CompletedAt *time.Time `json:"completed_at,omitempty" url:"completed_at,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (i *Import) GetID() string {
	if i == nil {
		return ""
	}
	return i.ID
}

func (i *Import) GetObject() ImportObject {
	if i == nil {
		return ""
	}
	return i.Object
}

func (i *Import) GetStatus() ImportStatus {
	if i == nil {
		return ""
	}
	return i.Status
}

func (i *Import) GetResourceType() ImportResourceType {
	if i == nil {
		return ""
	}
	return i.ResourceType
}

func (i *Import) GetTotalRows() *int {
	if i == nil {
		return nil
	}
	return i.TotalRows
}

func (i *Import) GetProcessedRows() *int {
	if i == nil {
		return nil
	}
	return i.ProcessedRows
}

func (i *Import) GetSuccessCount() *int {
	if i == nil {
		return nil
	}
	return i.SuccessCount
}

func (i *Import) GetErrorCount() *int {
	if i == nil {
		return nil
	}
	return i.ErrorCount
}

func (i *Import) GetErrors() []*ImportErrorsItem {
	if i == nil {
		return nil
	}
	return i.Errors
}

func (i *Import) GetCreatedAt() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.CreatedAt
}

func (i *Import) GetCompletedAt() *time.Time {
	if i == nil {
		return nil
	}
	return i.CompletedAt
}

func (i *Import) GetExtraProperties() map[string]interface{} {
	return i.extraProperties
}

func (i *Import) UnmarshalJSON(data []byte) error {
	type embed Import
	var unmarshaler = struct {
		embed
		CreatedAt   *core.DateTime `json:"created_at"`
		CompletedAt *core.DateTime `json:"completed_at,omitempty"`
	}{
		embed: embed(*i),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*i = Import(unmarshaler.embed)
	i.CreatedAt = unmarshaler.CreatedAt.Time()
	i.CompletedAt = unmarshaler.CompletedAt.TimePtr()

	extraProperties, err := core.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties

	i._rawJSON = json.RawMessage(data)
	return nil
}

func (i *Import) MarshalJSON() ([]byte, error) {
	type embed Import
	var marshaler = struct {
		embed
		CreatedAt   *core.DateTime `json:"created_at"`
		CompletedAt *core.DateTime `json:"completed_at,omitempty"`
	}{
		embed:       embed(*i),
		CreatedAt:   core.NewDateTime(i.CreatedAt),
		CompletedAt: core.NewOptionalDateTime(i.CompletedAt),
	}
	return json.Marshal(marshaler)
}

func (i *Import) String() string {
	if len(i._rawJSON) > 0 {
		if value, err := core.StringifyJSON(i._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

// The created import job in 'pending' status.
type ImportCreateResponse struct {
	Data *Import `json:"data,omitempty" url:"data,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (i *ImportCreateResponse) GetData() *Import {
	if i == nil {
		return nil
	}
	return i.Data
}

func (i *ImportCreateResponse) GetExtraProperties() map[string]interface{} {
	return i.extraProperties
}

func (i *ImportCreateResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ImportCreateResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = ImportCreateResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties

	i._rawJSON = json.RawMessage(data)
	return nil
}

func (i *ImportCreateResponse) String() string {
	if len(i._rawJSON) > 0 {
		if value, err := core.StringifyJSON(i._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

type ImportErrorsItem struct {
	// Row number (1-based)
	Row int `json:"row" url:"row"`
	// Field that caused the error
	Field *string `json:"field,omitempty" url:"field,omitempty"`
	// Error message
	Message string `json:"message" url:"message"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (i *ImportErrorsItem) GetRow() int {
	if i == nil {
		return 0
	}
	return i.Row
}

func (i *ImportErrorsItem) GetField() *string {
	if i == nil {
		return nil
	}
	return i.Field
}

func (i *ImportErrorsItem) GetMessage() string {
	if i == nil {
		return ""
	}
	return i.Message
}

func (i *ImportErrorsItem) GetExtraProperties() map[string]interface{} {
	return i.extraProperties
}

func (i *ImportErrorsItem) UnmarshalJSON(data []byte) error {
	type unmarshaler ImportErrorsItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = ImportErrorsItem(value)

	extraProperties, err := core.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties

	i._rawJSON = json.RawMessage(data)
	return nil
}

func (i *ImportErrorsItem) String() string {
	if len(i._rawJSON) > 0 {
		if value, err := core.StringifyJSON(i._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

// Object type
type ImportObject string

const (
	ImportObjectImport ImportObject = "import"
)

func NewImportObjectFromString(s string) (ImportObject, error) {
	switch s {
	case "import":
		return ImportObjectImport, nil
	}
	var t ImportObject
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (i ImportObject) Ptr() *ImportObject {
	return &i
}

// The type of resource to import.
type ImportResourceType string

const (
	ImportResourceTypeCustomers ImportResourceType = "customers"
	ImportResourceTypeProducts  ImportResourceType = "products"
	ImportResourceTypeInvoices  ImportResourceType = "invoices"
)

func NewImportResourceTypeFromString(s string) (ImportResourceType, error) {
	switch s {
	case "customers":
		return ImportResourceTypeCustomers, nil
	case "products":
		return ImportResourceTypeProducts, nil
	case "invoices":
		return ImportResourceTypeInvoices, nil
	}
	var t ImportResourceType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (i ImportResourceType) Ptr() *ImportResourceType {
	return &i
}

// Import job status and progress.
type ImportRetrieveResponse struct {
	Data *Import `json:"data,omitempty" url:"data,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (i *ImportRetrieveResponse) GetData() *Import {
	if i == nil {
		return nil
	}
	return i.Data
}

func (i *ImportRetrieveResponse) GetExtraProperties() map[string]interface{} {
	return i.extraProperties
}

func (i *ImportRetrieveResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ImportRetrieveResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = ImportRetrieveResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties

	i._rawJSON = json.RawMessage(data)
	return nil
}

func (i *ImportRetrieveResponse) String() string {
	if len(i._rawJSON) > 0 {
		if value, err := core.StringifyJSON(i._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

// Import job status. pending: queued. validating: checking data. processing: creating records. completed: all rows imported. completed_with_errors: some rows failed. failed: import aborted.
type ImportStatus string

const (
	ImportStatusPending             ImportStatus = "pending"
	ImportStatusValidating          ImportStatus = "validating"
	ImportStatusProcessing          ImportStatus = "processing"
	ImportStatusCompleted           ImportStatus = "completed"
	ImportStatusCompletedWithErrors ImportStatus = "completed_with_errors"
	ImportStatusFailed              ImportStatus = "failed"
)

func NewImportStatusFromString(s string) (ImportStatus, error) {
	switch s {
	case "pending":
		return ImportStatusPending, nil
	case "validating":
		return ImportStatusValidating, nil
	case "processing":
		return ImportStatusProcessing, nil
	case "completed":
		return ImportStatusCompleted, nil
	case "completed_with_errors":
		return ImportStatusCompletedWithErrors, nil
	case "failed":
		return ImportStatusFailed, nil
	}
	var t ImportStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (i ImportStatus) Ptr() *ImportStatus {
	return &i
}

// Behavior when a duplicate record is found. skip: ignore the row. update: merge new data. error: fail the row.
type CreateImportRequestOnDuplicate string

const (
	CreateImportRequestOnDuplicateSkip   CreateImportRequestOnDuplicate = "skip"
	CreateImportRequestOnDuplicateUpdate CreateImportRequestOnDuplicate = "update"
	CreateImportRequestOnDuplicateError  CreateImportRequestOnDuplicate = "error"
)

func NewCreateImportRequestOnDuplicateFromString(s string) (CreateImportRequestOnDuplicate, error) {
	switch s {
	case "skip":
		return CreateImportRequestOnDuplicateSkip, nil
	case "update":
		return CreateImportRequestOnDuplicateUpdate, nil
	case "error":
		return CreateImportRequestOnDuplicateError, nil
	}
	var t CreateImportRequestOnDuplicate
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateImportRequestOnDuplicate) Ptr() *CreateImportRequestOnDuplicate {
	return &c
}

// The type of resource to import.
type CreateImportRequestResourceType string

const (
	CreateImportRequestResourceTypeCustomers CreateImportRequestResourceType = "customers"
	CreateImportRequestResourceTypeProducts  CreateImportRequestResourceType = "products"
	CreateImportRequestResourceTypeInvoices  CreateImportRequestResourceType = "invoices"
)

func NewCreateImportRequestResourceTypeFromString(s string) (CreateImportRequestResourceType, error) {
	switch s {
	case "customers":
		return CreateImportRequestResourceTypeCustomers, nil
	case "products":
		return CreateImportRequestResourceTypeProducts, nil
	case "invoices":
		return CreateImportRequestResourceTypeInvoices, nil
	}
	var t CreateImportRequestResourceType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateImportRequestResourceType) Ptr() *CreateImportRequestResourceType {
	return &c
}
