// This file was auto-generated by Fern from our API Definition.

package revkeen

import (
	json "encoding/json"
	fmt "fmt"
	core "github.com/revkeen/revkeen-go/core"
)

type CreateMeterRequest struct {
	// Human-readable meter name
	Name string `json:"name" url:"-"`
	// Event name to match against
	EventName string `json:"event_name" url:"-"`
	// Aggregation method
	Aggregation *CreateMeterRequestAggregation `json:"aggregation,omitempty" url:"-"`
	// URL-safe identifier
	Slug *string `json:"slug,omitempty" url:"-"`
	// Meter description
	Description *string `json:"description,omitempty" url:"-"`
	// Property key for sum/max/last aggregations
	ValueKey *string `json:"value_key,omitempty" url:"-"`
	// Filter conditions for matching events
	FilterConditions []map[string]interface{} `json:"filter_conditions,omitempty" url:"-"`
	// Property key for count_unique aggregation
	UniqueCountKey *string `json:"unique_count_key,omitempty" url:"-"`
	// Display unit name
	UnitName *string `json:"unit_name,omitempty" url:"-"`
	// Carry forward last value across periods
	CarryForward *bool `json:"carry_forward,omitempty" url:"-"`
	// Arbitrary key-value metadata
	Metadata map[string]interface{} `json:"metadata,omitempty" url:"-"`
	// Threshold percentages that trigger usage.threshold.reached webhooks.
	AlertThresholds []float64 `json:"alert_thresholds,omitempty" url:"-"`
}

type CreateMeterPriceRequest struct {
	// Pricing model
	PricingModel CreateMeterPriceRequestPricingModel `json:"pricing_model" url:"-"`
	// ISO 4217 currency code
	Currency string `json:"currency" url:"-"`
	// Price per unit in minor units (for per_unit)
	UnitAmountMinor *int `json:"unit_amount_minor,omitempty" url:"-"`
	// Base charge per period in minor units
	FlatFeeMinor *int `json:"flat_fee_minor,omitempty" url:"-"`
	// Units per package (for package model)
	PackageSize *int `json:"package_size,omitempty" url:"-"`
	// Merchant's cost per unit for margin intelligence
	CostPerUnitMinor *int `json:"cost_per_unit_minor,omitempty" url:"-"`
	// Tier configuration (for graduated and volume)
	Tiers []*CreateMeterPriceRequestTiersItem `json:"tiers,omitempty" url:"-"`
}

type DeactivatePriceMetersRequest struct {
}

type GetMetersRequest struct {
}

type ListMetersRequest struct {
	// Include archived meters
	IncludeArchived *string `json:"-" url:"include_archived,omitempty"`
	// Max results (default 50, max 100)
	Limit *string `json:"-" url:"limit,omitempty"`
	// Pagination offset
	Offset *string `json:"-" url:"offset,omitempty"`
}

type ListPricesMetersRequest struct {
}

// The newly created meter object.
type CreateMeterResponse struct {
	// Created meter object
	Data map[string]interface{} `json:"data,omitempty" url:"data,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CreateMeterResponse) GetData() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.Data
}

func (c *CreateMeterResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreateMeterResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateMeterResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateMeterResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateMeterResponse) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// A single meter object with configuration details.
type MeterGetResponse struct {
	// Meter object
	Data map[string]interface{} `json:"data,omitempty" url:"data,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (m *MeterGetResponse) GetData() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.Data
}

func (m *MeterGetResponse) GetExtraProperties() map[string]interface{} {
	return m.extraProperties
}

func (m *MeterGetResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler MeterGetResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MeterGetResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties

	m._rawJSON = json.RawMessage(data)
	return nil
}

func (m *MeterGetResponse) String() string {
	if len(m._rawJSON) > 0 {
		if value, err := core.StringifyJSON(m._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

// A list of meters for the merchant.
type MeterListResponse struct {
	// Array of meter objects
	Data       []map[string]interface{}     `json:"data,omitempty" url:"data,omitempty"`
	Pagination *MeterListResponsePagination `json:"pagination,omitempty" url:"pagination,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (m *MeterListResponse) GetData() []map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.Data
}

func (m *MeterListResponse) GetPagination() *MeterListResponsePagination {
	if m == nil {
		return nil
	}
	return m.Pagination
}

func (m *MeterListResponse) GetExtraProperties() map[string]interface{} {
	return m.extraProperties
}

func (m *MeterListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler MeterListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MeterListResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties

	m._rawJSON = json.RawMessage(data)
	return nil
}

func (m *MeterListResponse) String() string {
	if len(m._rawJSON) > 0 {
		if value, err := core.StringifyJSON(m._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

type MeterListResponsePagination struct {
	Limit  float64 `json:"limit" url:"limit"`
	Offset float64 `json:"offset" url:"offset"`
	Count  float64 `json:"count" url:"count"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (m *MeterListResponsePagination) GetLimit() float64 {
	if m == nil {
		return 0
	}
	return m.Limit
}

func (m *MeterListResponsePagination) GetOffset() float64 {
	if m == nil {
		return 0
	}
	return m.Offset
}

func (m *MeterListResponsePagination) GetCount() float64 {
	if m == nil {
		return 0
	}
	return m.Count
}

func (m *MeterListResponsePagination) GetExtraProperties() map[string]interface{} {
	return m.extraProperties
}

func (m *MeterListResponsePagination) UnmarshalJSON(data []byte) error {
	type unmarshaler MeterListResponsePagination
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MeterListResponsePagination(value)

	extraProperties, err := core.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties

	m._rawJSON = json.RawMessage(data)
	return nil
}

func (m *MeterListResponsePagination) String() string {
	if len(m._rawJSON) > 0 {
		if value, err := core.StringifyJSON(m._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

// A list of prices attached to a meter.
type MeterPriceListResponse struct {
	// Array of price objects
	Data []map[string]interface{} `json:"data,omitempty" url:"data,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (m *MeterPriceListResponse) GetData() []map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.Data
}

func (m *MeterPriceListResponse) GetExtraProperties() map[string]interface{} {
	return m.extraProperties
}

func (m *MeterPriceListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler MeterPriceListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MeterPriceListResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties

	m._rawJSON = json.RawMessage(data)
	return nil
}

func (m *MeterPriceListResponse) String() string {
	if len(m._rawJSON) > 0 {
		if value, err := core.StringifyJSON(m._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

// A single meter price with per-unit cost and billing configuration.
type MeterPriceResponse struct {
	// Price object with tiers
	Data map[string]interface{} `json:"data,omitempty" url:"data,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (m *MeterPriceResponse) GetData() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.Data
}

func (m *MeterPriceResponse) GetExtraProperties() map[string]interface{} {
	return m.extraProperties
}

func (m *MeterPriceResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler MeterPriceResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MeterPriceResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties

	m._rawJSON = json.RawMessage(data)
	return nil
}

func (m *MeterPriceResponse) String() string {
	if len(m._rawJSON) > 0 {
		if value, err := core.StringifyJSON(m._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

// The updated meter object reflecting the changes.
type UpdateMeterResponse struct {
	// Updated meter object
	Data map[string]interface{} `json:"data,omitempty" url:"data,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (u *UpdateMeterResponse) GetData() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.Data
}

func (u *UpdateMeterResponse) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UpdateMeterResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateMeterResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdateMeterResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties

	u._rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdateMeterResponse) String() string {
	if len(u._rawJSON) > 0 {
		if value, err := core.StringifyJSON(u._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

// Pricing model
type CreateMeterPriceRequestPricingModel string

const (
	CreateMeterPriceRequestPricingModelPerUnit   CreateMeterPriceRequestPricingModel = "per_unit"
	CreateMeterPriceRequestPricingModelGraduated CreateMeterPriceRequestPricingModel = "graduated"
	CreateMeterPriceRequestPricingModelVolume    CreateMeterPriceRequestPricingModel = "volume"
	CreateMeterPriceRequestPricingModelPackage   CreateMeterPriceRequestPricingModel = "package"
)

func NewCreateMeterPriceRequestPricingModelFromString(s string) (CreateMeterPriceRequestPricingModel, error) {
	switch s {
	case "per_unit":
		return CreateMeterPriceRequestPricingModelPerUnit, nil
	case "graduated":
		return CreateMeterPriceRequestPricingModelGraduated, nil
	case "volume":
		return CreateMeterPriceRequestPricingModelVolume, nil
	case "package":
		return CreateMeterPriceRequestPricingModelPackage, nil
	}
	var t CreateMeterPriceRequestPricingModel
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateMeterPriceRequestPricingModel) Ptr() *CreateMeterPriceRequestPricingModel {
	return &c
}

type CreateMeterPriceRequestTiersItem struct {
	// Start of tier range
	FirstUnit int `json:"first_unit" url:"first_unit"`
	// End of tier range (null = unbounded)
	LastUnit *int `json:"last_unit,omitempty" url:"last_unit,omitempty"`
	// Per-unit price in this tier (minor units)
	UnitAmountMinor int `json:"unit_amount_minor" url:"unit_amount_minor"`
	// Flat fee for entering this tier (minor units)
	FlatAmountMinor *int `json:"flat_amount_minor,omitempty" url:"flat_amount_minor,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CreateMeterPriceRequestTiersItem) GetFirstUnit() int {
	if c == nil {
		return 0
	}
	return c.FirstUnit
}

func (c *CreateMeterPriceRequestTiersItem) GetLastUnit() *int {
	if c == nil {
		return nil
	}
	return c.LastUnit
}

func (c *CreateMeterPriceRequestTiersItem) GetUnitAmountMinor() int {
	if c == nil {
		return 0
	}
	return c.UnitAmountMinor
}

func (c *CreateMeterPriceRequestTiersItem) GetFlatAmountMinor() *int {
	if c == nil {
		return nil
	}
	return c.FlatAmountMinor
}

func (c *CreateMeterPriceRequestTiersItem) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreateMeterPriceRequestTiersItem) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateMeterPriceRequestTiersItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateMeterPriceRequestTiersItem(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateMeterPriceRequestTiersItem) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Aggregation method
type CreateMeterRequestAggregation string

const (
	CreateMeterRequestAggregationSum         CreateMeterRequestAggregation = "sum"
	CreateMeterRequestAggregationCount       CreateMeterRequestAggregation = "count"
	CreateMeterRequestAggregationCountUnique CreateMeterRequestAggregation = "count_unique"
	CreateMeterRequestAggregationMax         CreateMeterRequestAggregation = "max"
	CreateMeterRequestAggregationLast        CreateMeterRequestAggregation = "last"
)

func NewCreateMeterRequestAggregationFromString(s string) (CreateMeterRequestAggregation, error) {
	switch s {
	case "sum":
		return CreateMeterRequestAggregationSum, nil
	case "count":
		return CreateMeterRequestAggregationCount, nil
	case "count_unique":
		return CreateMeterRequestAggregationCountUnique, nil
	case "max":
		return CreateMeterRequestAggregationMax, nil
	case "last":
		return CreateMeterRequestAggregationLast, nil
	}
	var t CreateMeterRequestAggregation
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateMeterRequestAggregation) Ptr() *CreateMeterRequestAggregation {
	return &c
}

type UpdateMeterPriceRequestTiersItem struct {
	// Start of tier range
	FirstUnit int `json:"first_unit" url:"first_unit"`
	// End of tier range (null = unbounded)
	LastUnit *int `json:"last_unit,omitempty" url:"last_unit,omitempty"`
	// Per-unit price in this tier (minor units)
	UnitAmountMinor int `json:"unit_amount_minor" url:"unit_amount_minor"`
	// Flat fee for entering this tier (minor units)
	FlatAmountMinor *int `json:"flat_amount_minor,omitempty" url:"flat_amount_minor,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (u *UpdateMeterPriceRequestTiersItem) GetFirstUnit() int {
	if u == nil {
		return 0
	}
	return u.FirstUnit
}

func (u *UpdateMeterPriceRequestTiersItem) GetLastUnit() *int {
	if u == nil {
		return nil
	}
	return u.LastUnit
}

func (u *UpdateMeterPriceRequestTiersItem) GetUnitAmountMinor() int {
	if u == nil {
		return 0
	}
	return u.UnitAmountMinor
}

func (u *UpdateMeterPriceRequestTiersItem) GetFlatAmountMinor() *int {
	if u == nil {
		return nil
	}
	return u.FlatAmountMinor
}

func (u *UpdateMeterPriceRequestTiersItem) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UpdateMeterPriceRequestTiersItem) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateMeterPriceRequestTiersItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdateMeterPriceRequestTiersItem(value)

	extraProperties, err := core.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties

	u._rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdateMeterPriceRequestTiersItem) String() string {
	if len(u._rawJSON) > 0 {
		if value, err := core.StringifyJSON(u._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

// Meter status
type UpdateMeterRequestStatus string

const (
	UpdateMeterRequestStatusActive   UpdateMeterRequestStatus = "active"
	UpdateMeterRequestStatusArchived UpdateMeterRequestStatus = "archived"
	UpdateMeterRequestStatusDraft    UpdateMeterRequestStatus = "draft"
)

func NewUpdateMeterRequestStatusFromString(s string) (UpdateMeterRequestStatus, error) {
	switch s {
	case "active":
		return UpdateMeterRequestStatusActive, nil
	case "archived":
		return UpdateMeterRequestStatusArchived, nil
	case "draft":
		return UpdateMeterRequestStatusDraft, nil
	}
	var t UpdateMeterRequestStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (u UpdateMeterRequestStatus) Ptr() *UpdateMeterRequestStatus {
	return &u
}

type UpdateMeterRequest struct {
	// Updated meter name
	Name *string `json:"name,omitempty" url:"-"`
	// Updated slug
	Slug *string `json:"slug,omitempty" url:"-"`
	// Updated description
	Description *string `json:"description,omitempty" url:"-"`
	// Meter status
	Status *UpdateMeterRequestStatus `json:"status,omitempty" url:"-"`
	// Updated value key
	ValueKey *string `json:"value_key,omitempty" url:"-"`
	// Updated filter conditions
	FilterConditions []map[string]interface{} `json:"filter_conditions,omitempty" url:"-"`
	// Updated unique count key
	UniqueCountKey *string `json:"unique_count_key,omitempty" url:"-"`
	// Updated unit name
	UnitName *string `json:"unit_name,omitempty" url:"-"`
	// Updated carry forward setting
	CarryForward *bool `json:"carry_forward,omitempty" url:"-"`
	// Updated metadata
	Metadata map[string]interface{} `json:"metadata,omitempty" url:"-"`
	// Updated threshold percentages for usage.threshold.reached webhooks.
	AlertThresholds []float64 `json:"alert_thresholds,omitempty" url:"-"`
}

type UpdateMeterPriceRequest struct {
	UnitAmountMinor  *int                                `json:"unit_amount_minor,omitempty" url:"-"`
	FlatFeeMinor     *int                                `json:"flat_fee_minor,omitempty" url:"-"`
	PackageSize      *int                                `json:"package_size,omitempty" url:"-"`
	CostPerUnitMinor *int                                `json:"cost_per_unit_minor,omitempty" url:"-"`
	Tiers            []*UpdateMeterPriceRequestTiersItem `json:"tiers,omitempty" url:"-"`
}
