// This file was auto-generated by Fern from our API Definition.

package revkeen

import (
	json "encoding/json"
	fmt "fmt"
	core "github.com/revkeen/revkeen-go/core"
	time "time"
)

type CancelOrderRequest struct {
	// Reason for cancellation
	Reason *string `json:"reason,omitempty" url:"-"`
}

type CreateOrderRequest struct {
	// Customer ID (optional for guest orders)
	CustomerID *string `json:"customer_id,omitempty" url:"-"`
	// Three-letter ISO currency code
	Currency *string `json:"currency,omitempty" url:"-"`
	// Billing type. one_time: Single purchase. recurring: Subscription-based.
	BillingType *CreateOrderRequestBillingType `json:"billing_type,omitempty" url:"-"`
	// Order line items (at least one required)
	LineItems []*CreateOrderRequestLineItemsItem `json:"line_items,omitempty" url:"-"`
	// Custom key-value metadata
	Metadata map[string]interface{} `json:"metadata,omitempty" url:"-"`
	Notes    *string                `json:"notes,omitempty" url:"-"`
	// Expiration timestamp for the order
	ExpiresAt *time.Time `json:"expires_at,omitempty" url:"-"`
	// ID of the linked invoice (Commercial Truth)
	InvoiceID *string `json:"invoice_id,omitempty" url:"-"`
	// ID of the linked subscription (for recurring fulfillment)
	SubscriptionID *string `json:"subscription_id,omitempty" url:"-"`
}

func (c *CreateOrderRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateOrderRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateOrderRequest(body)
	return nil
}

func (c *CreateOrderRequest) MarshalJSON() ([]byte, error) {
	type embed CreateOrderRequest
	var marshaler = struct {
		embed
		ExpiresAt *core.DateTime `json:"expires_at,omitempty"`
	}{
		embed:     embed(*c),
		ExpiresAt: core.NewOptionalDateTime(c.ExpiresAt),
	}
	return json.Marshal(marshaler)
}

type FulfillOrderRequest struct {
	// Shipping tracking number
	TrackingNumber *string `json:"tracking_number,omitempty" url:"-"`
	// Shipping carrier (e.g., 'ups', 'fedex', 'usps')
	Carrier *string `json:"carrier,omitempty" url:"-"`
	// Specific line items to fulfill (defaults to all)
	LineItemIDs []string `json:"line_item_ids,omitempty" url:"-"`
	// Send fulfillment notification to customer
	NotifyCustomer *bool `json:"notify_customer,omitempty" url:"-"`
}

type OrdersListRequest struct {
	// Filter by customer ID
	CustomerID *string `json:"-" url:"customer_id,omitempty"`
	// Filter by status
	Status *OrdersListRequestStatus `json:"-" url:"status,omitempty"`
	// Filter by billing type
	BillingType *OrdersListRequestBillingType `json:"-" url:"billing_type,omitempty"`
	// Filter by created_at >= (Unix timestamp)
	CreatedGte *float64 `json:"-" url:"created_gte,omitempty"`
	// Filter by created_at <= (Unix timestamp)
	CreatedLte *float64 `json:"-" url:"created_lte,omitempty"`
	// Maximum number of results (1-100)
	Limit *int `json:"-" url:"limit,omitempty"`
	// Cursor for pagination - return results after this ID
	StartingAfter *string `json:"-" url:"starting_after,omitempty"`
	// Cursor for pagination - return results before this ID
	EndingBefore *string `json:"-" url:"ending_before,omitempty"`
}

type PayOrderRequest struct {
	// Saved payment method ID
	PaymentMethodID *string `json:"payment_method_id,omitempty" url:"-"`
	// One-time payment token
	PaymentToken *string `json:"payment_token,omitempty" url:"-"`
	// Partial payment amount in cents (defaults to full amount_due)
	Amount *int `json:"amount,omitempty" url:"-"`
}

type OrdersRetrieveRequest struct {
}

// An order represents a one-off purchase with lifecycle operations: create, pay, cancel, and fulfill.
type Order struct {
	// Unique identifier for the order
	ID string `json:"id" url:"id"`
	// Object type
	Object OrderObject `json:"object" url:"object"`
	// Public-facing order ID
	PublicID string `json:"public_id" url:"public_id"`
	// ID of the customer
	CustomerID *string `json:"customer_id,omitempty" url:"customer_id,omitempty"`
	// Order status. draft: Being built. pending: Awaiting payment. paid: Fully paid. partially_paid: Partial payment received. refunded: Refunded. canceled: Canceled. fulfilled: Shipped/delivered.
	Status OrderStatus `json:"status" url:"status"`
	// Billing type. one_time: Single purchase. recurring: Subscription-based.
	BillingType OrderBillingType `json:"billing_type" url:"billing_type"`
	// Fulfillment status for physical goods.
	FulfillmentStatus *OrderFulfillmentStatus `json:"fulfillment_status,omitempty" url:"fulfillment_status,omitempty"`
	// Three-letter ISO currency code
	Currency string `json:"currency" url:"currency"`
	// Subtotal in cents
	Subtotal int `json:"subtotal" url:"subtotal"`
	// Total discount in cents
	Discount int `json:"discount" url:"discount"`
	// Total tax in cents
	Tax int `json:"tax" url:"tax"`
	// Total amount in cents
	Total int `json:"total" url:"total"`
	// Amount paid in cents
	AmountPaid int `json:"amount_paid" url:"amount_paid"`
	// Amount refunded in cents
	AmountRefunded int `json:"amount_refunded" url:"amount_refunded"`
	// Amount still due in cents
	AmountDue int              `json:"amount_due" url:"amount_due"`
	LineItems []*OrderLineItem `json:"line_items,omitempty" url:"line_items,omitempty"`
	// Custom key-value metadata
	Metadata map[string]interface{} `json:"metadata,omitempty" url:"metadata,omitempty"`
	Notes    *string                `json:"notes,omitempty" url:"notes,omitempty"`
	// ID of the linked invoice (Commercial Truth)
	InvoiceID *string `json:"invoice_id,omitempty" url:"invoice_id,omitempty"`
	// ID of the linked subscription (for recurring fulfillment)
	SubscriptionID *string    `json:"subscription_id,omitempty" url:"subscription_id,omitempty"`
	CreatedAt      time.Time  `json:"created_at" url:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at" url:"updated_at"`
	PaidAt         *time.Time `json:"paid_at,omitempty" url:"paid_at,omitempty"`
	CanceledAt     *time.Time `json:"canceled_at,omitempty" url:"canceled_at,omitempty"`
	FulfilledAt    *time.Time `json:"fulfilled_at,omitempty" url:"fulfilled_at,omitempty"`
	ExpiresAt      *time.Time `json:"expires_at,omitempty" url:"expires_at,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (o *Order) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *Order) GetObject() OrderObject {
	if o == nil {
		return ""
	}
	return o.Object
}

func (o *Order) GetPublicID() string {
	if o == nil {
		return ""
	}
	return o.PublicID
}

func (o *Order) GetCustomerID() *string {
	if o == nil {
		return nil
	}
	return o.CustomerID
}

func (o *Order) GetStatus() OrderStatus {
	if o == nil {
		return ""
	}
	return o.Status
}

func (o *Order) GetBillingType() OrderBillingType {
	if o == nil {
		return ""
	}
	return o.BillingType
}

func (o *Order) GetFulfillmentStatus() *OrderFulfillmentStatus {
	if o == nil {
		return nil
	}
	return o.FulfillmentStatus
}

func (o *Order) GetCurrency() string {
	if o == nil {
		return ""
	}
	return o.Currency
}

func (o *Order) GetSubtotal() int {
	if o == nil {
		return 0
	}
	return o.Subtotal
}

func (o *Order) GetDiscount() int {
	if o == nil {
		return 0
	}
	return o.Discount
}

func (o *Order) GetTax() int {
	if o == nil {
		return 0
	}
	return o.Tax
}

func (o *Order) GetTotal() int {
	if o == nil {
		return 0
	}
	return o.Total
}

func (o *Order) GetAmountPaid() int {
	if o == nil {
		return 0
	}
	return o.AmountPaid
}

func (o *Order) GetAmountRefunded() int {
	if o == nil {
		return 0
	}
	return o.AmountRefunded
}

func (o *Order) GetAmountDue() int {
	if o == nil {
		return 0
	}
	return o.AmountDue
}

func (o *Order) GetLineItems() []*OrderLineItem {
	if o == nil {
		return nil
	}
	return o.LineItems
}

func (o *Order) GetMetadata() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.Metadata
}

func (o *Order) GetNotes() *string {
	if o == nil {
		return nil
	}
	return o.Notes
}

func (o *Order) GetInvoiceID() *string {
	if o == nil {
		return nil
	}
	return o.InvoiceID
}

func (o *Order) GetSubscriptionID() *string {
	if o == nil {
		return nil
	}
	return o.SubscriptionID
}

func (o *Order) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *Order) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}

func (o *Order) GetPaidAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.PaidAt
}

func (o *Order) GetCanceledAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CanceledAt
}

func (o *Order) GetFulfilledAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.FulfilledAt
}

func (o *Order) GetExpiresAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.ExpiresAt
}

func (o *Order) GetExtraProperties() map[string]interface{} {
	return o.extraProperties
}

func (o *Order) UnmarshalJSON(data []byte) error {
	type embed Order
	var unmarshaler = struct {
		embed
		CreatedAt   *core.DateTime `json:"created_at"`
		UpdatedAt   *core.DateTime `json:"updated_at"`
		PaidAt      *core.DateTime `json:"paid_at,omitempty"`
		CanceledAt  *core.DateTime `json:"canceled_at,omitempty"`
		FulfilledAt *core.DateTime `json:"fulfilled_at,omitempty"`
		ExpiresAt   *core.DateTime `json:"expires_at,omitempty"`
	}{
		embed: embed(*o),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*o = Order(unmarshaler.embed)
	o.CreatedAt = unmarshaler.CreatedAt.Time()
	o.UpdatedAt = unmarshaler.UpdatedAt.Time()
	o.PaidAt = unmarshaler.PaidAt.TimePtr()
	o.CanceledAt = unmarshaler.CanceledAt.TimePtr()
	o.FulfilledAt = unmarshaler.FulfilledAt.TimePtr()
	o.ExpiresAt = unmarshaler.ExpiresAt.TimePtr()

	extraProperties, err := core.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties

	o._rawJSON = json.RawMessage(data)
	return nil
}

func (o *Order) MarshalJSON() ([]byte, error) {
	type embed Order
	var marshaler = struct {
		embed
		CreatedAt   *core.DateTime `json:"created_at"`
		UpdatedAt   *core.DateTime `json:"updated_at"`
		PaidAt      *core.DateTime `json:"paid_at,omitempty"`
		CanceledAt  *core.DateTime `json:"canceled_at,omitempty"`
		FulfilledAt *core.DateTime `json:"fulfilled_at,omitempty"`
		ExpiresAt   *core.DateTime `json:"expires_at,omitempty"`
	}{
		embed:       embed(*o),
		CreatedAt:   core.NewDateTime(o.CreatedAt),
		UpdatedAt:   core.NewDateTime(o.UpdatedAt),
		PaidAt:      core.NewOptionalDateTime(o.PaidAt),
		CanceledAt:  core.NewOptionalDateTime(o.CanceledAt),
		FulfilledAt: core.NewOptionalDateTime(o.FulfilledAt),
		ExpiresAt:   core.NewOptionalDateTime(o.ExpiresAt),
	}
	return json.Marshal(marshaler)
}

func (o *Order) String() string {
	if len(o._rawJSON) > 0 {
		if value, err := core.StringifyJSON(o._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

// Billing type. one_time: Single purchase. recurring: Subscription-based.
type OrderBillingType string

const (
	OrderBillingTypeOneTime   OrderBillingType = "one_time"
	OrderBillingTypeRecurring OrderBillingType = "recurring"
)

func NewOrderBillingTypeFromString(s string) (OrderBillingType, error) {
	switch s {
	case "one_time":
		return OrderBillingTypeOneTime, nil
	case "recurring":
		return OrderBillingTypeRecurring, nil
	}
	var t OrderBillingType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (o OrderBillingType) Ptr() *OrderBillingType {
	return &o
}

// Fulfillment status for physical goods.
type OrderFulfillmentStatus string

const (
	OrderFulfillmentStatusUnfulfilled OrderFulfillmentStatus = "unfulfilled"
	OrderFulfillmentStatusPartial     OrderFulfillmentStatus = "partial"
	OrderFulfillmentStatusFulfilled   OrderFulfillmentStatus = "fulfilled"
	OrderFulfillmentStatusReturned    OrderFulfillmentStatus = "returned"
)

func NewOrderFulfillmentStatusFromString(s string) (OrderFulfillmentStatus, error) {
	switch s {
	case "unfulfilled":
		return OrderFulfillmentStatusUnfulfilled, nil
	case "partial":
		return OrderFulfillmentStatusPartial, nil
	case "fulfilled":
		return OrderFulfillmentStatusFulfilled, nil
	case "returned":
		return OrderFulfillmentStatusReturned, nil
	}
	var t OrderFulfillmentStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (o OrderFulfillmentStatus) Ptr() *OrderFulfillmentStatus {
	return &o
}

// A line item within an order, representing a product, quantity, and unit price.
type OrderLineItem struct {
	ID          string  `json:"id" url:"id"`
	ProductID   *string `json:"product_id,omitempty" url:"product_id,omitempty"`
	Description string  `json:"description" url:"description"`
	Quantity    int     `json:"quantity" url:"quantity"`
	// Unit price in cents
	UnitPrice int `json:"unit_price" url:"unit_price"`
	// Subtotal in cents (unit_price * quantity)
	Subtotal int `json:"subtotal" url:"subtotal"`
	// Discount in cents
	Discount *int `json:"discount,omitempty" url:"discount,omitempty"`
	// Tax in cents
	Tax *int `json:"tax,omitempty" url:"tax,omitempty"`
	// Total in cents (subtotal - discount + tax)
	Total int `json:"total" url:"total"`
	// Custom key-value metadata
	Metadata map[string]interface{} `json:"metadata,omitempty" url:"metadata,omitempty"`
	Position *int                   `json:"position,omitempty" url:"position,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (o *OrderLineItem) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *OrderLineItem) GetProductID() *string {
	if o == nil {
		return nil
	}
	return o.ProductID
}

func (o *OrderLineItem) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *OrderLineItem) GetQuantity() int {
	if o == nil {
		return 0
	}
	return o.Quantity
}

func (o *OrderLineItem) GetUnitPrice() int {
	if o == nil {
		return 0
	}
	return o.UnitPrice
}

func (o *OrderLineItem) GetSubtotal() int {
	if o == nil {
		return 0
	}
	return o.Subtotal
}

func (o *OrderLineItem) GetDiscount() *int {
	if o == nil {
		return nil
	}
	return o.Discount
}

func (o *OrderLineItem) GetTax() *int {
	if o == nil {
		return nil
	}
	return o.Tax
}

func (o *OrderLineItem) GetTotal() int {
	if o == nil {
		return 0
	}
	return o.Total
}

func (o *OrderLineItem) GetMetadata() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.Metadata
}

func (o *OrderLineItem) GetPosition() *int {
	if o == nil {
		return nil
	}
	return o.Position
}

func (o *OrderLineItem) GetExtraProperties() map[string]interface{} {
	return o.extraProperties
}

func (o *OrderLineItem) UnmarshalJSON(data []byte) error {
	type unmarshaler OrderLineItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*o = OrderLineItem(value)

	extraProperties, err := core.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties

	o._rawJSON = json.RawMessage(data)
	return nil
}

func (o *OrderLineItem) String() string {
	if len(o._rawJSON) > 0 {
		if value, err := core.StringifyJSON(o._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

// A paginated list of orders matching the query filters.
type OrderListResponse struct {
	Object     OrderListResponseObject `json:"object" url:"object"`
	Data       []*Order                `json:"data,omitempty" url:"data,omitempty"`
	HasMore    bool                    `json:"has_more" url:"has_more"`
	TotalCount *int                    `json:"total_count,omitempty" url:"total_count,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (o *OrderListResponse) GetObject() OrderListResponseObject {
	if o == nil {
		return ""
	}
	return o.Object
}

func (o *OrderListResponse) GetData() []*Order {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *OrderListResponse) GetHasMore() bool {
	if o == nil {
		return false
	}
	return o.HasMore
}

func (o *OrderListResponse) GetTotalCount() *int {
	if o == nil {
		return nil
	}
	return o.TotalCount
}

func (o *OrderListResponse) GetExtraProperties() map[string]interface{} {
	return o.extraProperties
}

func (o *OrderListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler OrderListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*o = OrderListResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties

	o._rawJSON = json.RawMessage(data)
	return nil
}

func (o *OrderListResponse) String() string {
	if len(o._rawJSON) > 0 {
		if value, err := core.StringifyJSON(o._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

type OrderListResponseObject string

const (
	OrderListResponseObjectList OrderListResponseObject = "list"
)

func NewOrderListResponseObjectFromString(s string) (OrderListResponseObject, error) {
	switch s {
	case "list":
		return OrderListResponseObjectList, nil
	}
	var t OrderListResponseObject
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (o OrderListResponseObject) Ptr() *OrderListResponseObject {
	return &o
}

// Object type
type OrderObject string

const (
	OrderObjectOrder OrderObject = "order"
)

func NewOrderObjectFromString(s string) (OrderObject, error) {
	switch s {
	case "order":
		return OrderObjectOrder, nil
	}
	var t OrderObject
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (o OrderObject) Ptr() *OrderObject {
	return &o
}

// Order status. draft: Being built. pending: Awaiting payment. paid: Fully paid. partially_paid: Partial payment received. refunded: Refunded. canceled: Canceled. fulfilled: Shipped/delivered.
type OrderStatus string

const (
	OrderStatusDraft         OrderStatus = "draft"
	OrderStatusPending       OrderStatus = "pending"
	OrderStatusPaid          OrderStatus = "paid"
	OrderStatusPartiallyPaid OrderStatus = "partially_paid"
	OrderStatusRefunded      OrderStatus = "refunded"
	OrderStatusCanceled      OrderStatus = "canceled"
	OrderStatusFulfilled     OrderStatus = "fulfilled"
)

func NewOrderStatusFromString(s string) (OrderStatus, error) {
	switch s {
	case "draft":
		return OrderStatusDraft, nil
	case "pending":
		return OrderStatusPending, nil
	case "paid":
		return OrderStatusPaid, nil
	case "partially_paid":
		return OrderStatusPartiallyPaid, nil
	case "refunded":
		return OrderStatusRefunded, nil
	case "canceled":
		return OrderStatusCanceled, nil
	case "fulfilled":
		return OrderStatusFulfilled, nil
	}
	var t OrderStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (o OrderStatus) Ptr() *OrderStatus {
	return &o
}

// Billing type. one_time: Single purchase. recurring: Subscription-based.
type CreateOrderRequestBillingType string

const (
	CreateOrderRequestBillingTypeOneTime   CreateOrderRequestBillingType = "one_time"
	CreateOrderRequestBillingTypeRecurring CreateOrderRequestBillingType = "recurring"
)

func NewCreateOrderRequestBillingTypeFromString(s string) (CreateOrderRequestBillingType, error) {
	switch s {
	case "one_time":
		return CreateOrderRequestBillingTypeOneTime, nil
	case "recurring":
		return CreateOrderRequestBillingTypeRecurring, nil
	}
	var t CreateOrderRequestBillingType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateOrderRequestBillingType) Ptr() *CreateOrderRequestBillingType {
	return &c
}

type CreateOrderRequestLineItemsItem struct {
	// Product ID (optional for ad-hoc items)
	ProductID   *string `json:"product_id,omitempty" url:"product_id,omitempty"`
	Description string  `json:"description" url:"description"`
	Quantity    *int    `json:"quantity,omitempty" url:"quantity,omitempty"`
	// Unit price in cents
	UnitPrice int `json:"unit_price" url:"unit_price"`
	// Custom key-value metadata
	Metadata map[string]interface{} `json:"metadata,omitempty" url:"metadata,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (c *CreateOrderRequestLineItemsItem) GetProductID() *string {
	if c == nil {
		return nil
	}
	return c.ProductID
}

func (c *CreateOrderRequestLineItemsItem) GetDescription() string {
	if c == nil {
		return ""
	}
	return c.Description
}

func (c *CreateOrderRequestLineItemsItem) GetQuantity() *int {
	if c == nil {
		return nil
	}
	return c.Quantity
}

func (c *CreateOrderRequestLineItemsItem) GetUnitPrice() int {
	if c == nil {
		return 0
	}
	return c.UnitPrice
}

func (c *CreateOrderRequestLineItemsItem) GetMetadata() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.Metadata
}

func (c *CreateOrderRequestLineItemsItem) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreateOrderRequestLineItemsItem) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateOrderRequestLineItemsItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateOrderRequestLineItemsItem(value)

	extraProperties, err := core.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties

	c._rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateOrderRequestLineItemsItem) String() string {
	if len(c._rawJSON) > 0 {
		if value, err := core.StringifyJSON(c._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Filter by billing type
type OrdersListRequestBillingType string

const (
	OrdersListRequestBillingTypeOneTime   OrdersListRequestBillingType = "one_time"
	OrdersListRequestBillingTypeRecurring OrdersListRequestBillingType = "recurring"
)

func NewOrdersListRequestBillingTypeFromString(s string) (OrdersListRequestBillingType, error) {
	switch s {
	case "one_time":
		return OrdersListRequestBillingTypeOneTime, nil
	case "recurring":
		return OrdersListRequestBillingTypeRecurring, nil
	}
	var t OrdersListRequestBillingType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (o OrdersListRequestBillingType) Ptr() *OrdersListRequestBillingType {
	return &o
}

// Filter by status
type OrdersListRequestStatus string

const (
	OrdersListRequestStatusDraft         OrdersListRequestStatus = "draft"
	OrdersListRequestStatusPending       OrdersListRequestStatus = "pending"
	OrdersListRequestStatusPaid          OrdersListRequestStatus = "paid"
	OrdersListRequestStatusPartiallyPaid OrdersListRequestStatus = "partially_paid"
	OrdersListRequestStatusRefunded      OrdersListRequestStatus = "refunded"
	OrdersListRequestStatusCanceled      OrdersListRequestStatus = "canceled"
	OrdersListRequestStatusFulfilled     OrdersListRequestStatus = "fulfilled"
)

func NewOrdersListRequestStatusFromString(s string) (OrdersListRequestStatus, error) {
	switch s {
	case "draft":
		return OrdersListRequestStatusDraft, nil
	case "pending":
		return OrdersListRequestStatusPending, nil
	case "paid":
		return OrdersListRequestStatusPaid, nil
	case "partially_paid":
		return OrdersListRequestStatusPartiallyPaid, nil
	case "refunded":
		return OrdersListRequestStatusRefunded, nil
	case "canceled":
		return OrdersListRequestStatusCanceled, nil
	case "fulfilled":
		return OrdersListRequestStatusFulfilled, nil
	}
	var t OrdersListRequestStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (o OrdersListRequestStatus) Ptr() *OrdersListRequestStatus {
	return &o
}
