// This file was auto-generated by Fern from our API Definition.

package revkeen

import (
	json "encoding/json"
	fmt "fmt"
	core "github.com/revkeen/revkeen-go/core"
	time "time"
)

type CancelPaymentIntentRequest struct {
	// Reason for cancellation
	CancellationReason *CancelPaymentIntentRequestCancellationReason `json:"cancellation_reason,omitempty" url:"-"`
}

type CapturePaymentIntentRequest struct {
	// Amount to capture in cents. Defaults to full authorized amount.
	AmountToCapture *int `json:"amount_to_capture,omitempty" url:"-"`
}

type ConfirmPaymentIntentRequest struct {
	// Payment method ID. Required if not already set on the intent.
	PaymentMethod *string `json:"payment_method,omitempty" url:"-"`
	// URL to redirect to after 3DS authentication
	ReturnURL *string `json:"return_url,omitempty" url:"-"`
}

type CreatePaymentIntentRequest struct {
	// Amount in cents. Must be greater than 0.
	Amount int `json:"amount" url:"-"`
	// Three-letter ISO currency code. Defaults to USD.
	Currency *string `json:"currency,omitempty" url:"-"`
	// Customer ID to charge
	Customer string `json:"customer" url:"-"`
	// Payment method ID. If not provided, status will be requires_payment_method.
	PaymentMethod *string `json:"payment_method,omitempty" url:"-"`
	// Capture method. Defaults to automatic.
	CaptureMethod *CreatePaymentIntentRequestCaptureMethod `json:"capture_method,omitempty" url:"-"`
	// Description for merchant reference
	Description *string `json:"description,omitempty" url:"-"`
	// Statement descriptor shown on customer's statement
	StatementDescriptor *string `json:"statement_descriptor,omitempty" url:"-"`
	// Statement descriptor suffix
	StatementDescriptorSuffix *string `json:"statement_descriptor_suffix,omitempty" url:"-"`
	// Email to send receipt to
	ReceiptEmail *string `json:"receipt_email,omitempty" url:"-"`
	// Custom key-value metadata
	Metadata map[string]interface{} `json:"metadata,omitempty" url:"-"`
	// Specific gateway merchant ID for multi-MID setups (NMI)
	GatewayMerchantID *string `json:"gateway_merchant_id,omitempty" url:"-"`
}

type PaymentIntentsListRequest struct {
	// Filter by customer ID
	Customer *string `json:"-" url:"customer,omitempty"`
	// Filter by status
	Status *PaymentIntentsListRequestStatus `json:"-" url:"status,omitempty"`
	// Filter by created_at >= (Unix timestamp)
	CreatedGte *float64 `json:"-" url:"created_gte,omitempty"`
	// Filter by created_at <= (Unix timestamp)
	CreatedLte *float64 `json:"-" url:"created_lte,omitempty"`
	// Maximum number of results (1-100)
	Limit *int `json:"-" url:"limit,omitempty"`
	// Cursor for pagination - return results after this ID (pi_xxx)
	StartingAfter *string `json:"-" url:"starting_after,omitempty"`
	// Cursor for pagination - return results before this ID (pi_xxx)
	EndingBefore *string `json:"-" url:"ending_before,omitempty"`
}

type PaymentIntentsRetrieveRequest struct {
}

// A PaymentIntent tracks the lifecycle of a payment from creation through authorization, optional 3DS authentication, and final capture.
type PaymentIntent struct {
	// Public payment intent ID (pi_xxx)
	ID string `json:"id" url:"id"`
	// Object type
	Object PaymentIntentObject `json:"object" url:"object"`
	// Amount in cents
	Amount int `json:"amount" url:"amount"`
	// Amount that can be captured (for manual capture)
	AmountCapturable int `json:"amount_capturable" url:"amount_capturable"`
	// Amount actually received
	AmountReceived int `json:"amount_received" url:"amount_received"`
	// Three-letter ISO currency code
	Currency string `json:"currency" url:"currency"`
	// Customer ID
	Customer string `json:"customer" url:"customer"`
	// Description for merchant reference
	Description *string `json:"description,omitempty" url:"description,omitempty"`
	// Last error from payment attempt
	LastPaymentError *PaymentIntentLastPaymentError `json:"last_payment_error,omitempty" url:"last_payment_error,omitempty"`
	// Custom key-value metadata
	Metadata map[string]interface{} `json:"metadata,omitempty" url:"metadata,omitempty"`
	// Action required from customer (3DS, etc.)
	NextAction *PaymentIntentNextAction `json:"next_action,omitempty" url:"next_action,omitempty"`
	// Payment method ID
	PaymentMethod *string `json:"payment_method,omitempty" url:"payment_method,omitempty"`
	// Email for receipt
	ReceiptEmail *string `json:"receipt_email,omitempty" url:"receipt_email,omitempty"`
	// Statement descriptor
	StatementDescriptor *string `json:"statement_descriptor,omitempty" url:"statement_descriptor,omitempty"`
	// Statement descriptor suffix
	StatementDescriptorSuffix *string `json:"statement_descriptor_suffix,omitempty" url:"statement_descriptor_suffix,omitempty"`
	// Payment intent status. requires_payment_method: Needs payment method. requires_confirmation: Ready to confirm. requires_action: Requires customer action (3DS). processing: Being processed. succeeded: Payment complete. canceled: Canceled.
	Status PaymentIntentStatus `json:"status" url:"status"`
	// Capture method. automatic: Capture immediately on confirmation. manual: Authorize then capture separately.
	CaptureMethod PaymentIntentCaptureMethod `json:"capture_method" url:"capture_method"`
	// Client secret for frontend confirmation
	ClientSecret string `json:"client_secret" url:"client_secret"`
	// When the intent was canceled
	CanceledAt *time.Time `json:"canceled_at,omitempty" url:"canceled_at,omitempty"`
	// Why the intent was canceled
	CancellationReason *PaymentIntentCancellationReason `json:"cancellation_reason,omitempty" url:"cancellation_reason,omitempty"`
	// Unix timestamp of creation
	Created int `json:"created" url:"created"`
	// Whether in live mode
	Livemode bool `json:"livemode" url:"livemode"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (p *PaymentIntent) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PaymentIntent) GetObject() PaymentIntentObject {
	if p == nil {
		return ""
	}
	return p.Object
}

func (p *PaymentIntent) GetAmount() int {
	if p == nil {
		return 0
	}
	return p.Amount
}

func (p *PaymentIntent) GetAmountCapturable() int {
	if p == nil {
		return 0
	}
	return p.AmountCapturable
}

func (p *PaymentIntent) GetAmountReceived() int {
	if p == nil {
		return 0
	}
	return p.AmountReceived
}

func (p *PaymentIntent) GetCurrency() string {
	if p == nil {
		return ""
	}
	return p.Currency
}

func (p *PaymentIntent) GetCustomer() string {
	if p == nil {
		return ""
	}
	return p.Customer
}

func (p *PaymentIntent) GetDescription() *string {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *PaymentIntent) GetLastPaymentError() *PaymentIntentLastPaymentError {
	if p == nil {
		return nil
	}
	return p.LastPaymentError
}

func (p *PaymentIntent) GetMetadata() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.Metadata
}

func (p *PaymentIntent) GetNextAction() *PaymentIntentNextAction {
	if p == nil {
		return nil
	}
	return p.NextAction
}

func (p *PaymentIntent) GetPaymentMethod() *string {
	if p == nil {
		return nil
	}
	return p.PaymentMethod
}

func (p *PaymentIntent) GetReceiptEmail() *string {
	if p == nil {
		return nil
	}
	return p.ReceiptEmail
}

func (p *PaymentIntent) GetStatementDescriptor() *string {
	if p == nil {
		return nil
	}
	return p.StatementDescriptor
}

func (p *PaymentIntent) GetStatementDescriptorSuffix() *string {
	if p == nil {
		return nil
	}
	return p.StatementDescriptorSuffix
}

func (p *PaymentIntent) GetStatus() PaymentIntentStatus {
	if p == nil {
		return ""
	}
	return p.Status
}

func (p *PaymentIntent) GetCaptureMethod() PaymentIntentCaptureMethod {
	if p == nil {
		return ""
	}
	return p.CaptureMethod
}

func (p *PaymentIntent) GetClientSecret() string {
	if p == nil {
		return ""
	}
	return p.ClientSecret
}

func (p *PaymentIntent) GetCanceledAt() *time.Time {
	if p == nil {
		return nil
	}
	return p.CanceledAt
}

func (p *PaymentIntent) GetCancellationReason() *PaymentIntentCancellationReason {
	if p == nil {
		return nil
	}
	return p.CancellationReason
}

func (p *PaymentIntent) GetCreated() int {
	if p == nil {
		return 0
	}
	return p.Created
}

func (p *PaymentIntent) GetLivemode() bool {
	if p == nil {
		return false
	}
	return p.Livemode
}

func (p *PaymentIntent) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PaymentIntent) UnmarshalJSON(data []byte) error {
	type embed PaymentIntent
	var unmarshaler = struct {
		embed
		CanceledAt *core.DateTime `json:"canceled_at,omitempty"`
	}{
		embed: embed(*p),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*p = PaymentIntent(unmarshaler.embed)
	p.CanceledAt = unmarshaler.CanceledAt.TimePtr()

	extraProperties, err := core.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties

	p._rawJSON = json.RawMessage(data)
	return nil
}

func (p *PaymentIntent) MarshalJSON() ([]byte, error) {
	type embed PaymentIntent
	var marshaler = struct {
		embed
		CanceledAt *core.DateTime `json:"canceled_at,omitempty"`
	}{
		embed:      embed(*p),
		CanceledAt: core.NewOptionalDateTime(p.CanceledAt),
	}
	return json.Marshal(marshaler)
}

func (p *PaymentIntent) String() string {
	if len(p._rawJSON) > 0 {
		if value, err := core.StringifyJSON(p._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

// Why the intent was canceled
type PaymentIntentCancellationReason string

const (
	PaymentIntentCancellationReasonDuplicate           PaymentIntentCancellationReason = "duplicate"
	PaymentIntentCancellationReasonFraudulent          PaymentIntentCancellationReason = "fraudulent"
	PaymentIntentCancellationReasonRequestedByCustomer PaymentIntentCancellationReason = "requested_by_customer"
	PaymentIntentCancellationReasonAbandoned           PaymentIntentCancellationReason = "abandoned"
	PaymentIntentCancellationReasonFailedInvoice       PaymentIntentCancellationReason = "failed_invoice"
)

func NewPaymentIntentCancellationReasonFromString(s string) (PaymentIntentCancellationReason, error) {
	switch s {
	case "duplicate":
		return PaymentIntentCancellationReasonDuplicate, nil
	case "fraudulent":
		return PaymentIntentCancellationReasonFraudulent, nil
	case "requested_by_customer":
		return PaymentIntentCancellationReasonRequestedByCustomer, nil
	case "abandoned":
		return PaymentIntentCancellationReasonAbandoned, nil
	case "failed_invoice":
		return PaymentIntentCancellationReasonFailedInvoice, nil
	}
	var t PaymentIntentCancellationReason
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p PaymentIntentCancellationReason) Ptr() *PaymentIntentCancellationReason {
	return &p
}

// Capture method. automatic: Capture immediately on confirmation. manual: Authorize then capture separately.
type PaymentIntentCaptureMethod string

const (
	PaymentIntentCaptureMethodAutomatic PaymentIntentCaptureMethod = "automatic"
	PaymentIntentCaptureMethodManual    PaymentIntentCaptureMethod = "manual"
)

func NewPaymentIntentCaptureMethodFromString(s string) (PaymentIntentCaptureMethod, error) {
	switch s {
	case "automatic":
		return PaymentIntentCaptureMethodAutomatic, nil
	case "manual":
		return PaymentIntentCaptureMethodManual, nil
	}
	var t PaymentIntentCaptureMethod
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p PaymentIntentCaptureMethod) Ptr() *PaymentIntentCaptureMethod {
	return &p
}

// Last error from payment attempt
type PaymentIntentLastPaymentError struct {
	// Error code
	Code string `json:"code" url:"code"`
	// Human-readable error message
	Message string `json:"message" url:"message"`
	// Card decline code if applicable
	DeclineCode *string `json:"decline_code,omitempty" url:"decline_code,omitempty"`
	// Payment method that caused the error
	PaymentMethod *PaymentIntentLastPaymentErrorPaymentMethod `json:"payment_method,omitempty" url:"payment_method,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (p *PaymentIntentLastPaymentError) GetCode() string {
	if p == nil {
		return ""
	}
	return p.Code
}

func (p *PaymentIntentLastPaymentError) GetMessage() string {
	if p == nil {
		return ""
	}
	return p.Message
}

func (p *PaymentIntentLastPaymentError) GetDeclineCode() *string {
	if p == nil {
		return nil
	}
	return p.DeclineCode
}

func (p *PaymentIntentLastPaymentError) GetPaymentMethod() *PaymentIntentLastPaymentErrorPaymentMethod {
	if p == nil {
		return nil
	}
	return p.PaymentMethod
}

func (p *PaymentIntentLastPaymentError) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PaymentIntentLastPaymentError) UnmarshalJSON(data []byte) error {
	type unmarshaler PaymentIntentLastPaymentError
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PaymentIntentLastPaymentError(value)

	extraProperties, err := core.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties

	p._rawJSON = json.RawMessage(data)
	return nil
}

func (p *PaymentIntentLastPaymentError) String() string {
	if len(p._rawJSON) > 0 {
		if value, err := core.StringifyJSON(p._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

// Payment method that caused the error
type PaymentIntentLastPaymentErrorPaymentMethod struct {
	// Payment method ID
	ID string `json:"id" url:"id"`
	// Payment method type
	Type string `json:"type" url:"type"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (p *PaymentIntentLastPaymentErrorPaymentMethod) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PaymentIntentLastPaymentErrorPaymentMethod) GetType() string {
	if p == nil {
		return ""
	}
	return p.Type
}

func (p *PaymentIntentLastPaymentErrorPaymentMethod) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PaymentIntentLastPaymentErrorPaymentMethod) UnmarshalJSON(data []byte) error {
	type unmarshaler PaymentIntentLastPaymentErrorPaymentMethod
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PaymentIntentLastPaymentErrorPaymentMethod(value)

	extraProperties, err := core.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties

	p._rawJSON = json.RawMessage(data)
	return nil
}

func (p *PaymentIntentLastPaymentErrorPaymentMethod) String() string {
	if len(p._rawJSON) > 0 {
		if value, err := core.StringifyJSON(p._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

// A paginated list of payment intents matching the query filters.
type PaymentIntentListResponse struct {
	Object  PaymentIntentListResponseObject `json:"object" url:"object"`
	Data    []*PaymentIntent                `json:"data,omitempty" url:"data,omitempty"`
	HasMore bool                            `json:"has_more" url:"has_more"`
	// The URL for accessing this list
	URL string `json:"url" url:"url"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (p *PaymentIntentListResponse) GetObject() PaymentIntentListResponseObject {
	if p == nil {
		return ""
	}
	return p.Object
}

func (p *PaymentIntentListResponse) GetData() []*PaymentIntent {
	if p == nil {
		return nil
	}
	return p.Data
}

func (p *PaymentIntentListResponse) GetHasMore() bool {
	if p == nil {
		return false
	}
	return p.HasMore
}

func (p *PaymentIntentListResponse) GetURL() string {
	if p == nil {
		return ""
	}
	return p.URL
}

func (p *PaymentIntentListResponse) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PaymentIntentListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler PaymentIntentListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PaymentIntentListResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties

	p._rawJSON = json.RawMessage(data)
	return nil
}

func (p *PaymentIntentListResponse) String() string {
	if len(p._rawJSON) > 0 {
		if value, err := core.StringifyJSON(p._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type PaymentIntentListResponseObject string

const (
	PaymentIntentListResponseObjectList PaymentIntentListResponseObject = "list"
)

func NewPaymentIntentListResponseObjectFromString(s string) (PaymentIntentListResponseObject, error) {
	switch s {
	case "list":
		return PaymentIntentListResponseObjectList, nil
	}
	var t PaymentIntentListResponseObject
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p PaymentIntentListResponseObject) Ptr() *PaymentIntentListResponseObject {
	return &p
}

// Action required from customer (3DS, etc.)
type PaymentIntentNextAction struct {
	// Type of action required
	Type PaymentIntentNextActionType `json:"type" url:"type"`
	// Present when type is redirect_to_url
	RedirectToURL *PaymentIntentNextActionRedirectToURL `json:"redirect_to_url,omitempty" url:"redirect_to_url,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (p *PaymentIntentNextAction) GetType() PaymentIntentNextActionType {
	if p == nil {
		return ""
	}
	return p.Type
}

func (p *PaymentIntentNextAction) GetRedirectToURL() *PaymentIntentNextActionRedirectToURL {
	if p == nil {
		return nil
	}
	return p.RedirectToURL
}

func (p *PaymentIntentNextAction) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PaymentIntentNextAction) UnmarshalJSON(data []byte) error {
	type unmarshaler PaymentIntentNextAction
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PaymentIntentNextAction(value)

	extraProperties, err := core.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties

	p._rawJSON = json.RawMessage(data)
	return nil
}

func (p *PaymentIntentNextAction) String() string {
	if len(p._rawJSON) > 0 {
		if value, err := core.StringifyJSON(p._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

// Present when type is redirect_to_url
type PaymentIntentNextActionRedirectToURL struct {
	// URL to redirect customer for 3DS authentication
	URL string `json:"url" url:"url"`
	// URL to return to after 3DS
	ReturnURL string `json:"return_url" url:"return_url"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (p *PaymentIntentNextActionRedirectToURL) GetURL() string {
	if p == nil {
		return ""
	}
	return p.URL
}

func (p *PaymentIntentNextActionRedirectToURL) GetReturnURL() string {
	if p == nil {
		return ""
	}
	return p.ReturnURL
}

func (p *PaymentIntentNextActionRedirectToURL) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PaymentIntentNextActionRedirectToURL) UnmarshalJSON(data []byte) error {
	type unmarshaler PaymentIntentNextActionRedirectToURL
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PaymentIntentNextActionRedirectToURL(value)

	extraProperties, err := core.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties

	p._rawJSON = json.RawMessage(data)
	return nil
}

func (p *PaymentIntentNextActionRedirectToURL) String() string {
	if len(p._rawJSON) > 0 {
		if value, err := core.StringifyJSON(p._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

// Type of action required
type PaymentIntentNextActionType string

const (
	PaymentIntentNextActionTypeRedirectToURL                   PaymentIntentNextActionType = "redirect_to_url"
	PaymentIntentNextActionTypeUseStripeSdk                    PaymentIntentNextActionType = "use_stripe_sdk"
	PaymentIntentNextActionTypeDisplayBankTransferInstructions PaymentIntentNextActionType = "display_bank_transfer_instructions"
)

func NewPaymentIntentNextActionTypeFromString(s string) (PaymentIntentNextActionType, error) {
	switch s {
	case "redirect_to_url":
		return PaymentIntentNextActionTypeRedirectToURL, nil
	case "use_stripe_sdk":
		return PaymentIntentNextActionTypeUseStripeSdk, nil
	case "display_bank_transfer_instructions":
		return PaymentIntentNextActionTypeDisplayBankTransferInstructions, nil
	}
	var t PaymentIntentNextActionType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p PaymentIntentNextActionType) Ptr() *PaymentIntentNextActionType {
	return &p
}

// Object type
type PaymentIntentObject string

const (
	PaymentIntentObjectPaymentIntent PaymentIntentObject = "payment_intent"
)

func NewPaymentIntentObjectFromString(s string) (PaymentIntentObject, error) {
	switch s {
	case "payment_intent":
		return PaymentIntentObjectPaymentIntent, nil
	}
	var t PaymentIntentObject
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p PaymentIntentObject) Ptr() *PaymentIntentObject {
	return &p
}

// Payment intent status. requires_payment_method: Needs payment method. requires_confirmation: Ready to confirm. requires_action: Requires customer action (3DS). processing: Being processed. succeeded: Payment complete. canceled: Canceled.
type PaymentIntentStatus string

const (
	PaymentIntentStatusRequiresPaymentMethod PaymentIntentStatus = "requires_payment_method"
	PaymentIntentStatusRequiresConfirmation  PaymentIntentStatus = "requires_confirmation"
	PaymentIntentStatusRequiresAction        PaymentIntentStatus = "requires_action"
	PaymentIntentStatusProcessing            PaymentIntentStatus = "processing"
	PaymentIntentStatusSucceeded             PaymentIntentStatus = "succeeded"
	PaymentIntentStatusCanceled              PaymentIntentStatus = "canceled"
)

func NewPaymentIntentStatusFromString(s string) (PaymentIntentStatus, error) {
	switch s {
	case "requires_payment_method":
		return PaymentIntentStatusRequiresPaymentMethod, nil
	case "requires_confirmation":
		return PaymentIntentStatusRequiresConfirmation, nil
	case "requires_action":
		return PaymentIntentStatusRequiresAction, nil
	case "processing":
		return PaymentIntentStatusProcessing, nil
	case "succeeded":
		return PaymentIntentStatusSucceeded, nil
	case "canceled":
		return PaymentIntentStatusCanceled, nil
	}
	var t PaymentIntentStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p PaymentIntentStatus) Ptr() *PaymentIntentStatus {
	return &p
}

// Reason for cancellation
type CancelPaymentIntentRequestCancellationReason string

const (
	CancelPaymentIntentRequestCancellationReasonDuplicate           CancelPaymentIntentRequestCancellationReason = "duplicate"
	CancelPaymentIntentRequestCancellationReasonFraudulent          CancelPaymentIntentRequestCancellationReason = "fraudulent"
	CancelPaymentIntentRequestCancellationReasonRequestedByCustomer CancelPaymentIntentRequestCancellationReason = "requested_by_customer"
	CancelPaymentIntentRequestCancellationReasonAbandoned           CancelPaymentIntentRequestCancellationReason = "abandoned"
	CancelPaymentIntentRequestCancellationReasonFailedInvoice       CancelPaymentIntentRequestCancellationReason = "failed_invoice"
)

func NewCancelPaymentIntentRequestCancellationReasonFromString(s string) (CancelPaymentIntentRequestCancellationReason, error) {
	switch s {
	case "duplicate":
		return CancelPaymentIntentRequestCancellationReasonDuplicate, nil
	case "fraudulent":
		return CancelPaymentIntentRequestCancellationReasonFraudulent, nil
	case "requested_by_customer":
		return CancelPaymentIntentRequestCancellationReasonRequestedByCustomer, nil
	case "abandoned":
		return CancelPaymentIntentRequestCancellationReasonAbandoned, nil
	case "failed_invoice":
		return CancelPaymentIntentRequestCancellationReasonFailedInvoice, nil
	}
	var t CancelPaymentIntentRequestCancellationReason
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CancelPaymentIntentRequestCancellationReason) Ptr() *CancelPaymentIntentRequestCancellationReason {
	return &c
}

// Capture method. Defaults to automatic.
type CreatePaymentIntentRequestCaptureMethod string

const (
	CreatePaymentIntentRequestCaptureMethodAutomatic CreatePaymentIntentRequestCaptureMethod = "automatic"
	CreatePaymentIntentRequestCaptureMethodManual    CreatePaymentIntentRequestCaptureMethod = "manual"
)

func NewCreatePaymentIntentRequestCaptureMethodFromString(s string) (CreatePaymentIntentRequestCaptureMethod, error) {
	switch s {
	case "automatic":
		return CreatePaymentIntentRequestCaptureMethodAutomatic, nil
	case "manual":
		return CreatePaymentIntentRequestCaptureMethodManual, nil
	}
	var t CreatePaymentIntentRequestCaptureMethod
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreatePaymentIntentRequestCaptureMethod) Ptr() *CreatePaymentIntentRequestCaptureMethod {
	return &c
}

// Filter by status
type PaymentIntentsListRequestStatus string

const (
	PaymentIntentsListRequestStatusRequiresPaymentMethod PaymentIntentsListRequestStatus = "requires_payment_method"
	PaymentIntentsListRequestStatusRequiresConfirmation  PaymentIntentsListRequestStatus = "requires_confirmation"
	PaymentIntentsListRequestStatusRequiresAction        PaymentIntentsListRequestStatus = "requires_action"
	PaymentIntentsListRequestStatusProcessing            PaymentIntentsListRequestStatus = "processing"
	PaymentIntentsListRequestStatusSucceeded             PaymentIntentsListRequestStatus = "succeeded"
	PaymentIntentsListRequestStatusCanceled              PaymentIntentsListRequestStatus = "canceled"
)

func NewPaymentIntentsListRequestStatusFromString(s string) (PaymentIntentsListRequestStatus, error) {
	switch s {
	case "requires_payment_method":
		return PaymentIntentsListRequestStatusRequiresPaymentMethod, nil
	case "requires_confirmation":
		return PaymentIntentsListRequestStatusRequiresConfirmation, nil
	case "requires_action":
		return PaymentIntentsListRequestStatusRequiresAction, nil
	case "processing":
		return PaymentIntentsListRequestStatusProcessing, nil
	case "succeeded":
		return PaymentIntentsListRequestStatusSucceeded, nil
	case "canceled":
		return PaymentIntentsListRequestStatusCanceled, nil
	}
	var t PaymentIntentsListRequestStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p PaymentIntentsListRequestStatus) Ptr() *PaymentIntentsListRequestStatus {
	return &p
}

type UpdatePaymentIntentRequest struct {
	// Amount in cents
	Amount *int `json:"amount,omitempty" url:"-"`
	// Three-letter ISO currency code
	Currency *string `json:"currency,omitempty" url:"-"`
	// Payment method ID
	PaymentMethod *string `json:"payment_method,omitempty" url:"-"`
	// Description for merchant reference
	Description *string `json:"description,omitempty" url:"-"`
	// Statement descriptor
	StatementDescriptor *string `json:"statement_descriptor,omitempty" url:"-"`
	// Statement descriptor suffix
	StatementDescriptorSuffix *string `json:"statement_descriptor_suffix,omitempty" url:"-"`
	// Email to send receipt to
	ReceiptEmail *string `json:"receipt_email,omitempty" url:"-"`
	// Custom key-value metadata
	Metadata map[string]interface{} `json:"metadata,omitempty" url:"-"`
}
