// This file was auto-generated by Fern from our API Definition.

package revkeen

import (
	json "encoding/json"
	fmt "fmt"
	core "github.com/revkeen/revkeen-go/core"
)

type PayoutsListRequest struct {
	// Filter by payout status
	Status *PayoutsListRequestStatus `json:"-" url:"status,omitempty"`
	// Filter by payment gateway (nmi, stripe, etc.)
	Gateway *string `json:"-" url:"gateway,omitempty"`
	// ISO 8601 date - only payouts created after this date
	CreatedAfter *string `json:"-" url:"created_after,omitempty"`
	// ISO 8601 date - only payouts created before this date
	CreatedBefore *string `json:"-" url:"created_before,omitempty"`
	// Number of results to return (1-100)
	Limit *float64 `json:"-" url:"limit,omitempty"`
	// Number of results to skip
	Offset *float64 `json:"-" url:"offset,omitempty"`
}

type PayoutsPaymentsListRequest struct {
	// Maximum number of results (1-100)
	Limit *float64 `json:"-" url:"limit,omitempty"`
	// Number of results to skip
	Offset *float64 `json:"-" url:"offset,omitempty"`
}

type PayoutsRetrieveRequest struct {
}

// A payout represents funds settled from processed payments to your bank account. Track settlement batches and reconcile amounts.
type Payout struct {
	ID              string `json:"id" url:"id"`
	PublicID        string `json:"public_id" url:"public_id"`
	Gateway         string `json:"gateway" url:"gateway"`
	GatewayPayoutID string `json:"gateway_payout_id" url:"gateway_payout_id"`
	// Gross amount in cents
	GrossAmountMinor float64 `json:"gross_amount_minor" url:"gross_amount_minor"`
	// Fees in cents
	FeesAmountMinor float64 `json:"fees_amount_minor" url:"fees_amount_minor"`
	// Net amount in cents
	NetAmountMinor   float64      `json:"net_amount_minor" url:"net_amount_minor"`
	Currency         string       `json:"currency" url:"currency"`
	ChargesCount     *float64     `json:"charges_count,omitempty" url:"charges_count,omitempty"`
	RefundsCount     *float64     `json:"refunds_count,omitempty" url:"refunds_count,omitempty"`
	ChargebacksCount *float64     `json:"chargebacks_count,omitempty" url:"chargebacks_count,omitempty"`
	Status           PayoutStatus `json:"status" url:"status"`
	ArrivalDate      *string      `json:"arrival_date,omitempty" url:"arrival_date,omitempty"`
	SettledAt        *string      `json:"settled_at,omitempty" url:"settled_at,omitempty"`
	CreatedAt        string       `json:"created_at" url:"created_at"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (p *Payout) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *Payout) GetPublicID() string {
	if p == nil {
		return ""
	}
	return p.PublicID
}

func (p *Payout) GetGateway() string {
	if p == nil {
		return ""
	}
	return p.Gateway
}

func (p *Payout) GetGatewayPayoutID() string {
	if p == nil {
		return ""
	}
	return p.GatewayPayoutID
}

func (p *Payout) GetGrossAmountMinor() float64 {
	if p == nil {
		return 0
	}
	return p.GrossAmountMinor
}

func (p *Payout) GetFeesAmountMinor() float64 {
	if p == nil {
		return 0
	}
	return p.FeesAmountMinor
}

func (p *Payout) GetNetAmountMinor() float64 {
	if p == nil {
		return 0
	}
	return p.NetAmountMinor
}

func (p *Payout) GetCurrency() string {
	if p == nil {
		return ""
	}
	return p.Currency
}

func (p *Payout) GetChargesCount() *float64 {
	if p == nil {
		return nil
	}
	return p.ChargesCount
}

func (p *Payout) GetRefundsCount() *float64 {
	if p == nil {
		return nil
	}
	return p.RefundsCount
}

func (p *Payout) GetChargebacksCount() *float64 {
	if p == nil {
		return nil
	}
	return p.ChargebacksCount
}

func (p *Payout) GetStatus() PayoutStatus {
	if p == nil {
		return ""
	}
	return p.Status
}

func (p *Payout) GetArrivalDate() *string {
	if p == nil {
		return nil
	}
	return p.ArrivalDate
}

func (p *Payout) GetSettledAt() *string {
	if p == nil {
		return nil
	}
	return p.SettledAt
}

func (p *Payout) GetCreatedAt() string {
	if p == nil {
		return ""
	}
	return p.CreatedAt
}

func (p *Payout) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *Payout) UnmarshalJSON(data []byte) error {
	type unmarshaler Payout
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = Payout(value)

	extraProperties, err := core.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties

	p._rawJSON = json.RawMessage(data)
	return nil
}

func (p *Payout) String() string {
	if len(p._rawJSON) > 0 {
		if value, err := core.StringifyJSON(p._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

// A payment included in a payout settlement batch, with amount and fee details.
type PayoutPayment struct {
	ID          string  `json:"id" url:"id"`
	PublicID    *string `json:"public_id,omitempty" url:"public_id,omitempty"`
	AmountMinor float64 `json:"amount_minor" url:"amount_minor"`
	Currency    string  `json:"currency" url:"currency"`
	Status      string  `json:"status" url:"status"`
	Kind        *string `json:"kind,omitempty" url:"kind,omitempty"`
	PaidAt      *string `json:"paid_at,omitempty" url:"paid_at,omitempty"`
	CreatedAt   string  `json:"created_at" url:"created_at"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (p *PayoutPayment) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PayoutPayment) GetPublicID() *string {
	if p == nil {
		return nil
	}
	return p.PublicID
}

func (p *PayoutPayment) GetAmountMinor() float64 {
	if p == nil {
		return 0
	}
	return p.AmountMinor
}

func (p *PayoutPayment) GetCurrency() string {
	if p == nil {
		return ""
	}
	return p.Currency
}

func (p *PayoutPayment) GetStatus() string {
	if p == nil {
		return ""
	}
	return p.Status
}

func (p *PayoutPayment) GetKind() *string {
	if p == nil {
		return nil
	}
	return p.Kind
}

func (p *PayoutPayment) GetPaidAt() *string {
	if p == nil {
		return nil
	}
	return p.PaidAt
}

func (p *PayoutPayment) GetCreatedAt() string {
	if p == nil {
		return ""
	}
	return p.CreatedAt
}

func (p *PayoutPayment) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PayoutPayment) UnmarshalJSON(data []byte) error {
	type unmarshaler PayoutPayment
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PayoutPayment(value)

	extraProperties, err := core.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties

	p._rawJSON = json.RawMessage(data)
	return nil
}

func (p *PayoutPayment) String() string {
	if len(p._rawJSON) > 0 {
		if value, err := core.StringifyJSON(p._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type PayoutStatus string

const (
	PayoutStatusPending   PayoutStatus = "pending"
	PayoutStatusInTransit PayoutStatus = "in_transit"
	PayoutStatusPaid      PayoutStatus = "paid"
	PayoutStatusFailed    PayoutStatus = "failed"
	PayoutStatusCanceled  PayoutStatus = "canceled"
)

func NewPayoutStatusFromString(s string) (PayoutStatus, error) {
	switch s {
	case "pending":
		return PayoutStatusPending, nil
	case "in_transit":
		return PayoutStatusInTransit, nil
	case "paid":
		return PayoutStatusPaid, nil
	case "failed":
		return PayoutStatusFailed, nil
	case "canceled":
		return PayoutStatusCanceled, nil
	}
	var t PayoutStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p PayoutStatus) Ptr() *PayoutStatus {
	return &p
}

// Filter by payout status
type PayoutsListRequestStatus string

const (
	PayoutsListRequestStatusPending   PayoutsListRequestStatus = "pending"
	PayoutsListRequestStatusInTransit PayoutsListRequestStatus = "in_transit"
	PayoutsListRequestStatusPaid      PayoutsListRequestStatus = "paid"
	PayoutsListRequestStatusFailed    PayoutsListRequestStatus = "failed"
	PayoutsListRequestStatusCanceled  PayoutsListRequestStatus = "canceled"
)

func NewPayoutsListRequestStatusFromString(s string) (PayoutsListRequestStatus, error) {
	switch s {
	case "pending":
		return PayoutsListRequestStatusPending, nil
	case "in_transit":
		return PayoutsListRequestStatusInTransit, nil
	case "paid":
		return PayoutsListRequestStatusPaid, nil
	case "failed":
		return PayoutsListRequestStatusFailed, nil
	case "canceled":
		return PayoutsListRequestStatusCanceled, nil
	}
	var t PayoutsListRequestStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p PayoutsListRequestStatus) Ptr() *PayoutsListRequestStatus {
	return &p
}

type PayoutsListResponse struct {
	Data []*Payout                `json:"data,omitempty" url:"data,omitempty"`
	Meta *PayoutsListResponseMeta `json:"meta,omitempty" url:"meta,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (p *PayoutsListResponse) GetData() []*Payout {
	if p == nil {
		return nil
	}
	return p.Data
}

func (p *PayoutsListResponse) GetMeta() *PayoutsListResponseMeta {
	if p == nil {
		return nil
	}
	return p.Meta
}

func (p *PayoutsListResponse) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PayoutsListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler PayoutsListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PayoutsListResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties

	p._rawJSON = json.RawMessage(data)
	return nil
}

func (p *PayoutsListResponse) String() string {
	if len(p._rawJSON) > 0 {
		if value, err := core.StringifyJSON(p._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type PayoutsListResponseMeta struct {
	Total   float64 `json:"total" url:"total"`
	Limit   float64 `json:"limit" url:"limit"`
	Offset  float64 `json:"offset" url:"offset"`
	HasMore bool    `json:"has_more" url:"has_more"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (p *PayoutsListResponseMeta) GetTotal() float64 {
	if p == nil {
		return 0
	}
	return p.Total
}

func (p *PayoutsListResponseMeta) GetLimit() float64 {
	if p == nil {
		return 0
	}
	return p.Limit
}

func (p *PayoutsListResponseMeta) GetOffset() float64 {
	if p == nil {
		return 0
	}
	return p.Offset
}

func (p *PayoutsListResponseMeta) GetHasMore() bool {
	if p == nil {
		return false
	}
	return p.HasMore
}

func (p *PayoutsListResponseMeta) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PayoutsListResponseMeta) UnmarshalJSON(data []byte) error {
	type unmarshaler PayoutsListResponseMeta
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PayoutsListResponseMeta(value)

	extraProperties, err := core.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties

	p._rawJSON = json.RawMessage(data)
	return nil
}

func (p *PayoutsListResponseMeta) String() string {
	if len(p._rawJSON) > 0 {
		if value, err := core.StringifyJSON(p._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type PayoutsPaymentsListResponse struct {
	Data []*PayoutPayment                 `json:"data,omitempty" url:"data,omitempty"`
	Meta *PayoutsPaymentsListResponseMeta `json:"meta,omitempty" url:"meta,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (p *PayoutsPaymentsListResponse) GetData() []*PayoutPayment {
	if p == nil {
		return nil
	}
	return p.Data
}

func (p *PayoutsPaymentsListResponse) GetMeta() *PayoutsPaymentsListResponseMeta {
	if p == nil {
		return nil
	}
	return p.Meta
}

func (p *PayoutsPaymentsListResponse) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PayoutsPaymentsListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler PayoutsPaymentsListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PayoutsPaymentsListResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties

	p._rawJSON = json.RawMessage(data)
	return nil
}

func (p *PayoutsPaymentsListResponse) String() string {
	if len(p._rawJSON) > 0 {
		if value, err := core.StringifyJSON(p._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type PayoutsPaymentsListResponseMeta struct {
	PayoutID string  `json:"payout_id" url:"payout_id"`
	Total    float64 `json:"total" url:"total"`
	Limit    float64 `json:"limit" url:"limit"`
	Offset   float64 `json:"offset" url:"offset"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (p *PayoutsPaymentsListResponseMeta) GetPayoutID() string {
	if p == nil {
		return ""
	}
	return p.PayoutID
}

func (p *PayoutsPaymentsListResponseMeta) GetTotal() float64 {
	if p == nil {
		return 0
	}
	return p.Total
}

func (p *PayoutsPaymentsListResponseMeta) GetLimit() float64 {
	if p == nil {
		return 0
	}
	return p.Limit
}

func (p *PayoutsPaymentsListResponseMeta) GetOffset() float64 {
	if p == nil {
		return 0
	}
	return p.Offset
}

func (p *PayoutsPaymentsListResponseMeta) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PayoutsPaymentsListResponseMeta) UnmarshalJSON(data []byte) error {
	type unmarshaler PayoutsPaymentsListResponseMeta
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PayoutsPaymentsListResponseMeta(value)

	extraProperties, err := core.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties

	p._rawJSON = json.RawMessage(data)
	return nil
}

func (p *PayoutsPaymentsListResponseMeta) String() string {
	if len(p._rawJSON) > 0 {
		if value, err := core.StringifyJSON(p._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type PayoutsRetrieveResponse struct {
	Data *Payout `json:"data,omitempty" url:"data,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (p *PayoutsRetrieveResponse) GetData() *Payout {
	if p == nil {
		return nil
	}
	return p.Data
}

func (p *PayoutsRetrieveResponse) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PayoutsRetrieveResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler PayoutsRetrieveResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PayoutsRetrieveResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties

	p._rawJSON = json.RawMessage(data)
	return nil
}

func (p *PayoutsRetrieveResponse) String() string {
	if len(p._rawJSON) > 0 {
		if value, err := core.StringifyJSON(p._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}
