// This file was auto-generated by Fern from our API Definition.

package revkeen

import (
	json "encoding/json"
	fmt "fmt"
	core "github.com/revkeen/revkeen-go/core"
)

type CancelTerminalPaymentsRequest struct {
}

type CreateTerminalPaymentRequest struct {
	// The ID of the terminal device to send the payment to. Use List Devices to discover available device IDs. Even merchants with a single terminal must pass the device_id explicitly — there is no auto-routing fallback.
	DeviceID string `json:"device_id" url:"-"`
	// Amount in minor units (e.g., pence for GBP, cents for USD)
	AmountMinor int `json:"amount_minor" url:"-"`
	// ISO 4217 currency code
	Currency string `json:"currency" url:"-"`
	// The invoice to charge. Omit for walk-in or ad-hoc payments where no invoice exists. When omitted, the terminal payment is recorded without an invoice association.
	InvoiceID *string `json:"invoice_id,omitempty" url:"-"`
	// Custom reference for the payment. Auto-generated if not provided.
	Reference *string `json:"reference,omitempty" url:"-"`
}

type ListTerminalPaymentsRequest struct {
	// Filter by invoice ID
	InvoiceID *string `json:"-" url:"invoice_id,omitempty"`
	// Filter by payment status
	Status *ListTerminalPaymentsRequestStatus `json:"-" url:"status,omitempty"`
	// Filter by payment type
	Type *ListTerminalPaymentsRequestType `json:"-" url:"type,omitempty"`
	// Filter by device ID
	DeviceID *string `json:"-" url:"device_id,omitempty"`
	// Maximum number of results (1-100)
	Limit *int `json:"-" url:"limit,omitempty"`
	// Cursor for pagination — return results after this terminal payment ID
	StartingAfter *string `json:"-" url:"starting_after,omitempty"`
}

type RefundTerminalPaymentRequest struct {
	// Amount to refund in minor units. Omit for a full refund.
	AmountMinor *int `json:"amount_minor,omitempty" url:"-"`
	// Reason for the refund
	Reason *string `json:"reason,omitempty" url:"-"`
}

type RetrieveTerminalPaymentsRequest struct {
}

// A card-present payment processed through a POS terminal, with device details and card entry mode.
type TerminalPayment struct {
	// Unique identifier for this terminal payment attempt
	ID string `json:"id" url:"id"`
	// Associated invoice ID, or null for walk-in/ad-hoc payments
	InvoiceID *string `json:"invoice_id,omitempty" url:"invoice_id,omitempty"`
	// The terminal device that processed (or is processing) this payment
	DeviceID *string `json:"device_id,omitempty" url:"device_id,omitempty"`
	// Transaction type. sale: original charge. refund: money returned. void: pre-settlement cancellation.
	Type TerminalPaymentType `json:"type" url:"type"`
	// Payment lifecycle status. requested: command sent, awaiting card. in_progress: terminal processing. approved: payment succeeded. declined: issuer declined. cancelled: merchant cancelled. error: terminal error. timed_out: no response within 3 minutes.
	Status TerminalPaymentStatus `json:"status" url:"status"`
	// Amount in minor units (e.g., pence for GBP, cents for USD)
	AmountMinor float64 `json:"amount_minor" url:"amount_minor"`
	// ISO 4217 currency code
	Currency string `json:"currency" url:"currency"`
	// Payment reference (invoice number or custom reference)
	Reference *string `json:"reference,omitempty" url:"reference,omitempty"`
	// Serial number of the PAX terminal that processed this payment
	TerminalSerial *string `json:"terminal_serial,omitempty" url:"terminal_serial,omitempty"`
	// Unique Transaction Identifier from the terminal
	Uti *string `json:"uti,omitempty" url:"uti,omitempty"`
	// Authorization code from the payment processor. Present when approved.
	AuthCode *string `json:"auth_code,omitempty" url:"auth_code,omitempty"`
	// Terminal response code. '00' indicates approval.
	ResponseCode *string `json:"response_code,omitempty" url:"response_code,omitempty"`
	// Retrieval Reference Number for settlement reconciliation
	Rrn *string `json:"rrn,omitempty" url:"rrn,omitempty"`
	// Card network (e.g., VISA, MASTERCARD, AMEX)
	CardScheme *string `json:"card_scheme,omitempty" url:"card_scheme,omitempty"`
	// Masked card number — only the last 4 digits are visible
	MaskedPan *string `json:"masked_pan,omitempty" url:"masked_pan,omitempty"`
	// How the card was read: contactless (NFC tap), emv_chip (chip insert), magnetic_stripe (swipe), manual_entry (keyed), or fallback (chip-to-swipe)
	EntryMode *string `json:"entry_mode,omitempty" url:"entry_mode,omitempty"`
	// Human-readable error message when status is error or timed_out
	ErrorMessage *string `json:"error_message,omitempty" url:"error_message,omitempty"`
	// ISO 8601 timestamp when the payment was initiated
	CreatedAt string `json:"created_at" url:"created_at"`
	// ISO 8601 timestamp when the terminal returned a result, or null if still in progress
	CompletedAt *string `json:"completed_at,omitempty" url:"completed_at,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (t *TerminalPayment) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *TerminalPayment) GetInvoiceID() *string {
	if t == nil {
		return nil
	}
	return t.InvoiceID
}

func (t *TerminalPayment) GetDeviceID() *string {
	if t == nil {
		return nil
	}
	return t.DeviceID
}

func (t *TerminalPayment) GetType() TerminalPaymentType {
	if t == nil {
		return ""
	}
	return t.Type
}

func (t *TerminalPayment) GetStatus() TerminalPaymentStatus {
	if t == nil {
		return ""
	}
	return t.Status
}

func (t *TerminalPayment) GetAmountMinor() float64 {
	if t == nil {
		return 0
	}
	return t.AmountMinor
}

func (t *TerminalPayment) GetCurrency() string {
	if t == nil {
		return ""
	}
	return t.Currency
}

func (t *TerminalPayment) GetReference() *string {
	if t == nil {
		return nil
	}
	return t.Reference
}

func (t *TerminalPayment) GetTerminalSerial() *string {
	if t == nil {
		return nil
	}
	return t.TerminalSerial
}

func (t *TerminalPayment) GetUti() *string {
	if t == nil {
		return nil
	}
	return t.Uti
}

func (t *TerminalPayment) GetAuthCode() *string {
	if t == nil {
		return nil
	}
	return t.AuthCode
}

func (t *TerminalPayment) GetResponseCode() *string {
	if t == nil {
		return nil
	}
	return t.ResponseCode
}

func (t *TerminalPayment) GetRrn() *string {
	if t == nil {
		return nil
	}
	return t.Rrn
}

func (t *TerminalPayment) GetCardScheme() *string {
	if t == nil {
		return nil
	}
	return t.CardScheme
}

func (t *TerminalPayment) GetMaskedPan() *string {
	if t == nil {
		return nil
	}
	return t.MaskedPan
}

func (t *TerminalPayment) GetEntryMode() *string {
	if t == nil {
		return nil
	}
	return t.EntryMode
}

func (t *TerminalPayment) GetErrorMessage() *string {
	if t == nil {
		return nil
	}
	return t.ErrorMessage
}

func (t *TerminalPayment) GetCreatedAt() string {
	if t == nil {
		return ""
	}
	return t.CreatedAt
}

func (t *TerminalPayment) GetCompletedAt() *string {
	if t == nil {
		return nil
	}
	return t.CompletedAt
}

func (t *TerminalPayment) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TerminalPayment) UnmarshalJSON(data []byte) error {
	type unmarshaler TerminalPayment
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TerminalPayment(value)

	extraProperties, err := core.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties

	t._rawJSON = json.RawMessage(data)
	return nil
}

func (t *TerminalPayment) String() string {
	if len(t._rawJSON) > 0 {
		if value, err := core.StringifyJSON(t._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

// A paginated list of terminal payments matching the query filters.
type TerminalPaymentListResponse struct {
	Data []*TerminalPayment               `json:"data,omitempty" url:"data,omitempty"`
	Meta *TerminalPaymentListResponseMeta `json:"meta,omitempty" url:"meta,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (t *TerminalPaymentListResponse) GetData() []*TerminalPayment {
	if t == nil {
		return nil
	}
	return t.Data
}

func (t *TerminalPaymentListResponse) GetMeta() *TerminalPaymentListResponseMeta {
	if t == nil {
		return nil
	}
	return t.Meta
}

func (t *TerminalPaymentListResponse) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TerminalPaymentListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler TerminalPaymentListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TerminalPaymentListResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties

	t._rawJSON = json.RawMessage(data)
	return nil
}

func (t *TerminalPaymentListResponse) String() string {
	if len(t._rawJSON) > 0 {
		if value, err := core.StringifyJSON(t._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

type TerminalPaymentListResponseMeta struct {
	Count float64 `json:"count" url:"count"`
	Limit float64 `json:"limit" url:"limit"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (t *TerminalPaymentListResponseMeta) GetCount() float64 {
	if t == nil {
		return 0
	}
	return t.Count
}

func (t *TerminalPaymentListResponseMeta) GetLimit() float64 {
	if t == nil {
		return 0
	}
	return t.Limit
}

func (t *TerminalPaymentListResponseMeta) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TerminalPaymentListResponseMeta) UnmarshalJSON(data []byte) error {
	type unmarshaler TerminalPaymentListResponseMeta
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TerminalPaymentListResponseMeta(value)

	extraProperties, err := core.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties

	t._rawJSON = json.RawMessage(data)
	return nil
}

func (t *TerminalPaymentListResponseMeta) String() string {
	if len(t._rawJSON) > 0 {
		if value, err := core.StringifyJSON(t._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

// A single terminal payment object with full device and transaction details.
type TerminalPaymentResponse struct {
	Data *TerminalPayment `json:"data,omitempty" url:"data,omitempty"`

	extraProperties map[string]interface{}
	_rawJSON        json.RawMessage
}

func (t *TerminalPaymentResponse) GetData() *TerminalPayment {
	if t == nil {
		return nil
	}
	return t.Data
}

func (t *TerminalPaymentResponse) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TerminalPaymentResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler TerminalPaymentResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TerminalPaymentResponse(value)

	extraProperties, err := core.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties

	t._rawJSON = json.RawMessage(data)
	return nil
}

func (t *TerminalPaymentResponse) String() string {
	if len(t._rawJSON) > 0 {
		if value, err := core.StringifyJSON(t._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

// Payment lifecycle status. requested: command sent, awaiting card. in_progress: terminal processing. approved: payment succeeded. declined: issuer declined. cancelled: merchant cancelled. error: terminal error. timed_out: no response within 3 minutes.
type TerminalPaymentStatus string

const (
	TerminalPaymentStatusRequested          TerminalPaymentStatus = "requested"
	TerminalPaymentStatusInProgress         TerminalPaymentStatus = "in_progress"
	TerminalPaymentStatusApproved           TerminalPaymentStatus = "approved"
	TerminalPaymentStatusDeclined           TerminalPaymentStatus = "declined"
	TerminalPaymentStatusCancelled          TerminalPaymentStatus = "cancelled"
	TerminalPaymentStatusError              TerminalPaymentStatus = "error"
	TerminalPaymentStatusTimedOut           TerminalPaymentStatus = "timed_out"
	TerminalPaymentStatusStandaloneApproved TerminalPaymentStatus = "standalone_approved"
	TerminalPaymentStatusStandaloneDeclined TerminalPaymentStatus = "standalone_declined"
)

func NewTerminalPaymentStatusFromString(s string) (TerminalPaymentStatus, error) {
	switch s {
	case "requested":
		return TerminalPaymentStatusRequested, nil
	case "in_progress":
		return TerminalPaymentStatusInProgress, nil
	case "approved":
		return TerminalPaymentStatusApproved, nil
	case "declined":
		return TerminalPaymentStatusDeclined, nil
	case "cancelled":
		return TerminalPaymentStatusCancelled, nil
	case "error":
		return TerminalPaymentStatusError, nil
	case "timed_out":
		return TerminalPaymentStatusTimedOut, nil
	case "standalone_approved":
		return TerminalPaymentStatusStandaloneApproved, nil
	case "standalone_declined":
		return TerminalPaymentStatusStandaloneDeclined, nil
	}
	var t TerminalPaymentStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (t TerminalPaymentStatus) Ptr() *TerminalPaymentStatus {
	return &t
}

// Transaction type. sale: original charge. refund: money returned. void: pre-settlement cancellation.
type TerminalPaymentType string

const (
	TerminalPaymentTypeSale   TerminalPaymentType = "sale"
	TerminalPaymentTypeRefund TerminalPaymentType = "refund"
	TerminalPaymentTypeVoid   TerminalPaymentType = "void"
)

func NewTerminalPaymentTypeFromString(s string) (TerminalPaymentType, error) {
	switch s {
	case "sale":
		return TerminalPaymentTypeSale, nil
	case "refund":
		return TerminalPaymentTypeRefund, nil
	case "void":
		return TerminalPaymentTypeVoid, nil
	}
	var t TerminalPaymentType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (t TerminalPaymentType) Ptr() *TerminalPaymentType {
	return &t
}

// Filter by payment status
type ListTerminalPaymentsRequestStatus string

const (
	ListTerminalPaymentsRequestStatusRequested  ListTerminalPaymentsRequestStatus = "requested"
	ListTerminalPaymentsRequestStatusInProgress ListTerminalPaymentsRequestStatus = "in_progress"
	ListTerminalPaymentsRequestStatusApproved   ListTerminalPaymentsRequestStatus = "approved"
	ListTerminalPaymentsRequestStatusDeclined   ListTerminalPaymentsRequestStatus = "declined"
	ListTerminalPaymentsRequestStatusCancelled  ListTerminalPaymentsRequestStatus = "cancelled"
	ListTerminalPaymentsRequestStatusError      ListTerminalPaymentsRequestStatus = "error"
	ListTerminalPaymentsRequestStatusTimedOut   ListTerminalPaymentsRequestStatus = "timed_out"
)

func NewListTerminalPaymentsRequestStatusFromString(s string) (ListTerminalPaymentsRequestStatus, error) {
	switch s {
	case "requested":
		return ListTerminalPaymentsRequestStatusRequested, nil
	case "in_progress":
		return ListTerminalPaymentsRequestStatusInProgress, nil
	case "approved":
		return ListTerminalPaymentsRequestStatusApproved, nil
	case "declined":
		return ListTerminalPaymentsRequestStatusDeclined, nil
	case "cancelled":
		return ListTerminalPaymentsRequestStatusCancelled, nil
	case "error":
		return ListTerminalPaymentsRequestStatusError, nil
	case "timed_out":
		return ListTerminalPaymentsRequestStatusTimedOut, nil
	}
	var t ListTerminalPaymentsRequestStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (l ListTerminalPaymentsRequestStatus) Ptr() *ListTerminalPaymentsRequestStatus {
	return &l
}

// Filter by payment type
type ListTerminalPaymentsRequestType string

const (
	ListTerminalPaymentsRequestTypeSale   ListTerminalPaymentsRequestType = "sale"
	ListTerminalPaymentsRequestTypeRefund ListTerminalPaymentsRequestType = "refund"
	ListTerminalPaymentsRequestTypeVoid   ListTerminalPaymentsRequestType = "void"
)

func NewListTerminalPaymentsRequestTypeFromString(s string) (ListTerminalPaymentsRequestType, error) {
	switch s {
	case "sale":
		return ListTerminalPaymentsRequestTypeSale, nil
	case "refund":
		return ListTerminalPaymentsRequestTypeRefund, nil
	case "void":
		return ListTerminalPaymentsRequestTypeVoid, nil
	}
	var t ListTerminalPaymentsRequestType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (l ListTerminalPaymentsRequestType) Ptr() *ListTerminalPaymentsRequestType {
	return &l
}

type VoidTerminalPaymentRequest struct {
	// Reason for the void
	Reason *string `json:"reason,omitempty" url:"-"`
}
