// This file was auto-generated by Fern from our API Definition.

// Refund objects represent money returned to a customer after a completed payment. You can issue full or partial refunds, and they automatically create a child transaction linked to the original payment for audit trail purposes.
// 
// **Required Scopes:**
// - `refunds:read` - List and retrieve refunds
// - `refunds:write` - Create refunds
// 
// **MCP Tools:** `refunds_create`
package refunds
