// This file was auto-generated by Fern from our API Definition.

// Query current-period usage balance with estimated costs per meter. Includes included allowance, overage, and margin data.
// 
// **Required Scopes:**
// - `usage:read` - Get usage balance
// 
// **MCP Tools:** `usage_balance_get`
package usage
