// This file was auto-generated by Fern from our API Definition.

// Customer objects represent the individuals or businesses you bill. Use them to store contact information, attach payment methods, and track billing history across subscriptions and one-off payments. Every charge, invoice, and subscription belongs to a customer.
// 
// **Required Scopes:**
// - `customers:read` - List and retrieve customers
// - `customers:write` - Create, update, delete customers
// 
// **MCP Tools:** `customers_list`, `customers_get`, `customers_create`, `customers_update`
package customers
