// This file was auto-generated by Fern from our API Definition.

// Create shareable payment links for invoices, subscriptions, or custom amounts. Customers complete payment on a hosted page.
// 
// **Required Scopes:**
// - `payment_links:read` - List and retrieve payment links
// - `payment_links:write` - Create and update payment links
package paymentlinks
