// This file was auto-generated by Fern from our API Definition.

// Subscriptions manage recurring billing cycles for your customers. Create subscriptions to automatically charge customers on a schedule, with support for trials, prorations, plan changes, and dunning for failed payments.
// 
// **Required Scopes:**
// - `subscriptions:read` - List and retrieve subscriptions
// - `subscriptions:write` - Create, update, cancel subscriptions
// 
// **MCP Tools:** `subscriptions_get`
package subscriptions
