// This file was auto-generated by Fern from our API Definition.

// Invoices are the canonical record of what a customer owes or has paid. Every subscription cycle generates an invoice automatically, and you can also create one-off invoices for ad-hoc charges. Invoices progress through a lifecycle: `draft` → `open` → `finalized` → `paid`.
// 
// **Required Scopes:**
// - `invoices:read` - List and retrieve invoices
// - `invoices:write` - Create, update, send, finalize invoices
// 
// **MCP Tools:** `invoices_list`, `invoices_get`, `invoices_create`, `invoices_send`, `invoices_finalize`
package invoices
