// This file was auto-generated by Fern from our API Definition.

// Create and manage usage meters. Meters define how usage events are aggregated for billing. Attach prices to meters for automated usage-based invoicing.
// 
// **Required Scopes:**
// - `prices:read` - List and retrieve meters and prices
// - `prices:write` - Create, update, archive meters and prices
// 
// **MCP Tools:** `meters_list`, `meters_get`, `meters_create`, `meters_update`, `meters_create_price`, `meters_list_prices`, `meters_update_price`, `meters_deactivate_price`
package meters
