// This file was auto-generated by Fern from our API Definition.

// Schedule future changes to subscriptions. Define phases with different pricing, quantities, or plans that take effect at specified dates.
// 
// **Required Scopes:**
// - `subscription_schedules:read` - List and retrieve schedules
// - `subscription_schedules:write` - Create, update, release schedules
package subscriptionschedules
