// This file was auto-generated by Fern from our API Definition.

// Webhook endpoint objects let you register URLs that RevKeen will notify when events occur in your account — payments, subscription changes, invoice updates, and more. Each endpoint can subscribe to specific event types or use wildcards to receive all events.
package webhookendpoints
